"""Unresolvability propagates through every combinator, in every input position.

This is the core promise of the decidability design: anything built on an
unanswerable sub-expression is itself unanswerable, with the reason intact. We
exercise each combinator with an ``Unresolvable`` input in each position so the
propagation branches are all covered.
"""

from __future__ import annotations

from collections.abc import Callable

import pytest

from fungeom import (
    CoordinateFrame,
    Coverage,
    Direction2,
    Direction3,
    Direction3Signal,
    Duration,
    Frame,
    Instant,
    Interval,
    Direction3Bundle,
    Line,
    Plane,
    Point3,
    Point3Bundle,
    Point3BundleSignal,
    Point3Signal,
    Ray,
    ScalarBundle,
    Segment,
    TransformBundle,
    Vec3Bundle,
    RigidTransform,
    Sampling,
    Scalar,
    ScalarSignal,
    TimeMap,
    TimeWarp,
    Timeline,
    Transform,
    TransformSignal,
    Unresolvable,
    Vec2,
    Vec3,
    Vec3Signal,
)

# One Unresolvable and one Resolvable resolver of each type.
BAD_S, GOOD_S = Scalar.of(1) / Scalar.of(0), Scalar.of(2)
BAD_V3, GOOD_V3 = Vec3.of(0, 0, 0).normalized(), Vec3.of(1, 0, 0)
BAD_V2, GOOD_V2 = Vec2.of(0, 0).normalized(), Vec2.of(1, 0)
BAD_T, GOOD_T = Transform.rotation(Vec3.of(0, 0, 0), Scalar.of(1)), Transform.identity()
BAD_D, GOOD_D = Direction3.of(0, 0, 0), Direction3.of(1, 0, 0)
BAD_D2, GOOD_D2 = Direction2.of(0, 0), Direction2.of(1, 0)
BAD_F, GOOD_F = Frame.detached("loose"), Frame.world
BAD_P = Point3.at(0, 0, 0, frame=CoordinateFrame.detached("loose"))
GOOD_P = Point3.at(0, 0, 0)
BAD_PLANE = Plane.through(BAD_P, GOOD_D)
GOOD_PLANE = Plane.through(GOOD_P, GOOD_D)
BAD_LINE = Line.through(BAD_P, GOOD_D)
GOOD_LINE = Line.through(GOOD_P, GOOD_D)
BAD_RAY = Ray.through(BAD_P, GOOD_D)
GOOD_RAY = Ray.through(GOOD_P, GOOD_D)
BAD_SEG = Segment.between(BAD_P, GOOD_P)
GOOD_SEG = Segment.between(GOOD_P, Point3.at(1, 0, 0))
BAD_DUR, GOOD_DUR = Duration.of(1).scale(BAD_S), Duration.of(2)
BAD_I, GOOD_I = Instant.epoch.shifted_by(BAD_DUR), Instant.at(0)
BAD_INT = Interval.between(BAD_I, GOOD_I)
GOOD_INT, GOOD_INT2 = Interval.between(Instant.at(0), Instant.at(10)), Interval.between(Instant.at(5), Instant.at(20))
BAD_COV = Coverage.of([BAD_INT])
BAD_TM, GOOD_TM = TimeMap.rate(0).inverse(), TimeMap.identity()
BAD_TW = TimeWarp.through([(1.0, 0.0), (0.0, 1.0)])  # non-monotonic source knots
GOOD_TW = TimeWarp.through([(0.0, 0.0), (2.0, 2.0)])
BAD_TL, GOOD_TL = Timeline.detached("loose"), Timeline.master
BAD_SAMP, GOOD_SAMP = Sampling.at_times([1, 0]), Sampling.at_times([0, 1])
BAD_SIG = ScalarSignal.from_samples([1, 0], [1, 2])
GOOD_SIG = ScalarSignal.from_samples([0, 1, 2], [10, 20, 30])
BAD_BUNDLE, GOOD_PB = Point3Bundle.of([BAD_P]), Point3Bundle.of([GOOD_P])
BAD_PBS = Point3BundleSignal.from_frames([1, 0], [[[0, 0, 0]], [[1, 0, 0]]])  # out-of-order sampling
GOOD_PBS = Point3BundleSignal.from_frames([0, 1], [[[0, 0, 0]], [[1, 0, 0]]])
BAD_VB, GOOD_VB = Vec3Bundle.of([BAD_V3]), Vec3Bundle.of([GOOD_V3])
BAD_SB, GOOD_SB = ScalarBundle.of([BAD_S]), ScalarBundle.of([GOOD_S])
BAD_DB = Direction3Bundle.of([BAD_D])
BAD_TB = TransformBundle.of([BAD_T])
BAD_VSIG = Vec3Signal.from_samples([1, 0], [[0, 0, 0], [1, 1, 1]])
GOOD_VSIG = Vec3Signal.from_samples([0, 1, 2], [[0, 0, 0], [1, 0, 0], [2, 0, 0]])
BAD_DSIG = Direction3Signal.from_samples([1, 0], [[1, 0, 0], [0, 1, 0]])
GOOD_DSIG = Direction3Signal.from_samples([0, 1, 2], [[1, 0, 0], [0, 1, 0], [0, 0, 1]])
_ID = RigidTransform.identity()
BAD_TSIG = TransformSignal.from_samples([1, 0], [_ID, _ID])
GOOD_TSIG = TransformSignal.from_samples([0, 1, 2], [_ID, _ID, _ID])
BAD_PSIG = Point3Signal.from_samples([1, 0], [[0, 0, 0], [1, 1, 1]])
GOOD_PSIG = Point3Signal.from_samples([0, 1, 2], [[0, 0, 0], [1, 0, 0], [2, 0, 0]])
GOOD_COV, GOOD_COV2 = Coverage.of([GOOD_INT]), Coverage.of([GOOD_INT2])
BAD_BOOL, GOOD_BOOL = BAD_S.lt(GOOD_S), GOOD_S.lt(Scalar.of(3))

CASES: dict[str, Callable[[], object]] = {
    # scalar (both positions for binaries)
    "scalar.add.lhs": lambda: BAD_S + GOOD_S,
    "scalar.add.rhs": lambda: GOOD_S + BAD_S,
    "scalar.sub": lambda: GOOD_S - BAD_S,
    "scalar.mul.lhs": lambda: BAD_S * GOOD_S,
    "scalar.mul.rhs": lambda: GOOD_S * BAD_S,
    "scalar.div.num": lambda: BAD_S / GOOD_S,
    "scalar.div.den": lambda: GOOD_S / BAD_S,
    "scalar.min.lhs": lambda: BAD_S.min(GOOD_S),
    "scalar.min.rhs": lambda: GOOD_S.min(BAD_S),
    "scalar.max.lhs": lambda: BAD_S.max(GOOD_S),
    "scalar.max.rhs": lambda: GOOD_S.max(BAD_S),
    "scalar.pow.base": lambda: BAD_S**GOOD_S,
    "scalar.pow.exp": lambda: GOOD_S**BAD_S,
    "scalar.clamp.v": lambda: BAD_S.clamp(GOOD_S, GOOD_S),
    "scalar.clamp.lo": lambda: GOOD_S.clamp(BAD_S, GOOD_S),
    "scalar.clamp.hi": lambda: GOOD_S.clamp(GOOD_S, BAD_S),
    "scalar.abs": lambda: abs(BAD_S),
    "scalar.sqrt": lambda: BAD_S.sqrt(),
    "scalar.sign": lambda: BAD_S.sign(),
    "scalar.floor": lambda: BAD_S.floor(),
    "scalar.ceil": lambda: BAD_S.ceil(),
    "scalar.round": lambda: BAD_S.round(),
    "scalar.mod.lhs": lambda: BAD_S.mod(GOOD_S),
    "scalar.mod.rhs": lambda: GOOD_S.mod(BAD_S),
    "scalar.lt.lhs": lambda: BAD_S.lt(GOOD_S),
    "scalar.lt.rhs": lambda: GOOD_S.lt(BAD_S),
    "scalar.le.lhs": lambda: BAD_S.le(GOOD_S),
    "scalar.le.rhs": lambda: GOOD_S.le(BAD_S),
    "scalar.gt.lhs": lambda: BAD_S.gt(GOOD_S),
    "scalar.gt.rhs": lambda: GOOD_S.gt(BAD_S),
    "scalar.ge.lhs": lambda: BAD_S.ge(GOOD_S),
    "scalar.ge.rhs": lambda: GOOD_S.ge(BAD_S),
    # bool (logical algebra; strict propagation)
    "bool.and.lhs": lambda: BAD_BOOL.and_(GOOD_BOOL),
    "bool.and.rhs": lambda: GOOD_BOOL.and_(BAD_BOOL),
    "bool.or.lhs": lambda: BAD_BOOL.or_(GOOD_BOOL),
    "bool.or.rhs": lambda: GOOD_BOOL.or_(BAD_BOOL),
    "bool.not": lambda: BAD_BOOL.not_(),
    # vec3
    "vec3.add.lhs": lambda: BAD_V3 + GOOD_V3,
    "vec3.add.rhs": lambda: GOOD_V3 + BAD_V3,
    "vec3.scale.vec": lambda: BAD_V3.scale(GOOD_S),
    "vec3.scale.factor": lambda: GOOD_V3.scale(BAD_S),
    "vec3.dot.lhs": lambda: BAD_V3.dot(GOOD_V3),
    "vec3.dot.rhs": lambda: GOOD_V3.dot(BAD_V3),
    "vec3.cross.lhs": lambda: BAD_V3.cross(GOOD_V3),
    "vec3.cross.rhs": lambda: GOOD_V3.cross(BAD_V3),
    "vec3.lerp.a": lambda: BAD_V3.lerp(GOOD_V3, GOOD_S),
    "vec3.lerp.b": lambda: GOOD_V3.lerp(BAD_V3, GOOD_S),
    "vec3.lerp.t": lambda: GOOD_V3.lerp(GOOD_V3, BAD_S),
    "vec3.proj.a": lambda: BAD_V3.project_onto(GOOD_V3),
    "vec3.proj.onto": lambda: GOOD_V3.project_onto(BAD_V3),
    "vec3.rej.a": lambda: BAD_V3.reject_from(GOOD_V3),
    "vec3.rej.onto": lambda: GOOD_V3.reject_from(BAD_V3),
    "vec3.norm": lambda: BAD_V3.norm(),
    "vec3.normalized": lambda: BAD_V3.normalized(),
    "vec3.coord": lambda: BAD_V3.x(),
    "vec3.angle.lhs": lambda: BAD_V3.angle_to(GOOD_V3),
    "vec3.angle.rhs": lambda: GOOD_V3.angle_to(BAD_V3),
    "vec3.with_norm.vec": lambda: BAD_V3.with_norm(GOOD_S),
    "vec3.with_norm.len": lambda: GOOD_V3.with_norm(BAD_S),
    # vec2
    "vec2.add.lhs": lambda: BAD_V2 + GOOD_V2,
    "vec2.add.rhs": lambda: GOOD_V2 + BAD_V2,
    "vec2.scale.vec": lambda: BAD_V2.scale(GOOD_S),
    "vec2.scale.factor": lambda: GOOD_V2.scale(BAD_S),
    "vec2.dot.lhs": lambda: BAD_V2.dot(GOOD_V2),
    "vec2.dot.rhs": lambda: GOOD_V2.dot(BAD_V2),
    "vec2.cross.lhs": lambda: BAD_V2.cross(GOOD_V2),
    "vec2.cross.rhs": lambda: GOOD_V2.cross(BAD_V2),
    "vec2.lerp.a": lambda: BAD_V2.lerp(GOOD_V2, GOOD_S),
    "vec2.lerp.b": lambda: GOOD_V2.lerp(BAD_V2, GOOD_S),
    "vec2.lerp.t": lambda: GOOD_V2.lerp(GOOD_V2, BAD_S),
    "vec2.proj.a": lambda: BAD_V2.project_onto(GOOD_V2),
    "vec2.proj.onto": lambda: GOOD_V2.project_onto(BAD_V2),
    "vec2.rej.a": lambda: BAD_V2.reject_from(GOOD_V2),
    "vec2.rej.onto": lambda: GOOD_V2.reject_from(BAD_V2),
    "vec2.components": lambda: Vec2.of(BAD_S, GOOD_S),
    "vec2.norm": lambda: BAD_V2.norm(),
    "vec2.normalized": lambda: BAD_V2.normalized(),
    "vec2.coord": lambda: BAD_V2.x(),
    "vec2.angle.lhs": lambda: BAD_V2.angle_to(GOOD_V2),
    "vec2.angle.rhs": lambda: GOOD_V2.angle_to(BAD_V2),
    "vec2.with_norm.vec": lambda: BAD_V2.with_norm(GOOD_S),
    "vec2.with_norm.len": lambda: GOOD_V2.with_norm(BAD_S),
    "vec2.perpendicular": lambda: BAD_V2.perpendicular(),
    # transform
    "tf.compose.a": lambda: BAD_T @ GOOD_T,
    "tf.compose.b": lambda: GOOD_T @ BAD_T,
    "tf.inverse": lambda: BAD_T.inverse(),
    "tf.slerp.a": lambda: BAD_T.slerp(GOOD_T, GOOD_S),
    "tf.slerp.b": lambda: GOOD_T.slerp(BAD_T, GOOD_S),
    "tf.slerp.t": lambda: GOOD_T.slerp(GOOD_T, BAD_S),
    "tf.rotation.axis": lambda: Transform.rotation(BAD_V3, GOOD_S),
    "tf.rotation.angle": lambda: Transform.rotation(GOOD_V3, BAD_S),
    "tf.translation": lambda: Transform.translation(BAD_V3),
    "tf.apply_vec.tf": lambda: BAD_T.transform_vector(GOOD_V3),
    "tf.apply_vec.vec": lambda: GOOD_T.transform_vector(BAD_V3),
    "tf.apply_dir.tf": lambda: BAD_T.transform_direction(GOOD_D),
    "tf.apply_dir.dir": lambda: GOOD_T.transform_direction(BAD_D),
    "tf.translation_part": lambda: BAD_T.translation_part(),
    "tf.rotation_part": lambda: BAD_T.rotation_part(),
    # direction
    "dir.reversed": lambda: BAD_D.reversed(),
    "dir.angle.lhs": lambda: BAD_D.angle_to(GOOD_D),
    "dir.angle.rhs": lambda: GOOD_D.angle_to(BAD_D),
    "dir.slerp.a": lambda: BAD_D.slerp(GOOD_D, GOOD_S),
    "dir.slerp.b": lambda: GOOD_D.slerp(BAD_D, GOOD_S),
    "dir.slerp.t": lambda: GOOD_D.slerp(GOOD_D, BAD_S),
    "dir.as_vector": lambda: BAD_D.as_vector(),
    "dir.towards": lambda: Direction3.towards(BAD_V3),
    "dir.dot.lhs": lambda: BAD_D.dot(GOOD_D),
    "dir.dot.rhs": lambda: GOOD_D.dot(BAD_D),
    "dir.cross.lhs": lambda: BAD_D.cross(GOOD_D),
    "dir.cross.rhs": lambda: GOOD_D.cross(BAD_D),
    "dir.any_perpendicular": lambda: BAD_D.any_perpendicular(),
    "dir2.of.scalar": lambda: Direction2.of(BAD_S, GOOD_S),
    "dir2.towards": lambda: Direction2.towards(BAD_V2),
    "dir2.reversed": lambda: BAD_D2.reversed(),
    "dir2.perpendicular": lambda: BAD_D2.perpendicular(),
    "dir2.angle": lambda: BAD_D2.angle(),
    "dir2.angle_to.lhs": lambda: BAD_D2.angle_to(GOOD_D2),
    "dir2.angle_to.rhs": lambda: GOOD_D2.angle_to(BAD_D2),
    "dir2.dot.lhs": lambda: BAD_D2.dot(GOOD_D2),
    "dir2.dot.rhs": lambda: GOOD_D2.dot(BAD_D2),
    "dir2.as_vector": lambda: BAD_D2.as_vector(),
    # frame
    "frame.attach.parent": lambda: BAD_F.attach("x", GOOD_T),
    "frame.attach.transform": lambda: GOOD_F.attach("x", BAD_T),
    "frame.relative.frame": lambda: BAD_F.relative_to(GOOD_F),
    "frame.relative.other": lambda: GOOD_F.relative_to(BAD_F),
    # point
    "pt.midpoint.a": lambda: BAD_P.midpoint(GOOD_P),
    "pt.midpoint.b": lambda: GOOD_P.midpoint(BAD_P),
    "pt.lerp.t": lambda: GOOD_P.lerp(GOOD_P, BAD_S),
    "pt.disp.a": lambda: BAD_P.displacement_to(GOOD_P),
    "pt.disp.b": lambda: GOOD_P.displacement_to(BAD_P),
    "pt.translate": lambda: GOOD_P.translate(BAD_V3),
    "pt.at.coord": lambda: Point3.at(BAD_S, 0, 0),
    "pt.in_frame.local": lambda: Point3.in_frame(BAD_V3, GOOD_F),
    "pt.in_frame.frame": lambda: Point3.in_frame(GOOD_V3, BAD_F),
    "pt.centroid": lambda: Point3.centroid([GOOD_P, BAD_P]),
    "pt.affine.point": lambda: Point3.affine([GOOD_P, BAD_P], [1, 1]),
    "pt.affine.weight": lambda: Point3.affine([GOOD_P, GOOD_P], [BAD_S, GOOD_S]),
    "pt.transformed.pt": lambda: BAD_P.transformed_by(GOOD_T),
    "pt.transformed.tf": lambda: GOOD_P.transformed_by(BAD_T),
    "pt.reflect.pt": lambda: BAD_P.reflect_across(GOOD_P),
    "pt.reflect.center": lambda: GOOD_P.reflect_across(BAD_P),
    # plane
    "plane.through.anchor": lambda: Plane.through(BAD_P, GOOD_D),
    "plane.through.axis": lambda: Plane.through(GOOD_P, BAD_D),
    "plane.through_points.a": lambda: Plane.through_points(BAD_P, GOOD_P, GOOD_P),
    "plane.through_points.b": lambda: Plane.through_points(GOOD_P, BAD_P, GOOD_P),
    "plane.through_points.c": lambda: Plane.through_points(GOOD_P, GOOD_P, BAD_P),
    "plane.spanned_by.anchor": lambda: Plane.spanned_by(BAD_P, GOOD_V3, GOOD_V3),
    "plane.spanned_by.u": lambda: Plane.spanned_by(GOOD_P, BAD_V3, GOOD_V3),
    "plane.spanned_by.v": lambda: Plane.spanned_by(GOOD_P, GOOD_V3, BAD_V3),
    "plane.normal": lambda: BAD_PLANE.normal(),
    "plane.origin": lambda: BAD_PLANE.origin(),
    "plane.project.plane": lambda: BAD_PLANE.project(GOOD_P),
    "plane.project.point": lambda: GOOD_PLANE.project(BAD_P),
    "plane.signed_distance.plane": lambda: BAD_PLANE.signed_distance(GOOD_P),
    "plane.signed_distance.point": lambda: GOOD_PLANE.signed_distance(BAD_P),
    "plane.distance_to": lambda: BAD_PLANE.distance_to(GOOD_P),
    "plane.contains": lambda: BAD_PLANE.contains(GOOD_P),
    "plane.facing.plane": lambda: BAD_PLANE.facing(GOOD_P),
    "plane.facing.point": lambda: GOOD_PLANE.facing(BAD_P),
    "plane.flipped": lambda: BAD_PLANE.flipped(),
    "plane.offset.plane": lambda: BAD_PLANE.offset(GOOD_S),
    "plane.offset.distance": lambda: GOOD_PLANE.offset(BAD_S),
    "plane.project_direction.plane": lambda: BAD_PLANE.project_direction(GOOD_D),
    "plane.project_direction.direction": lambda: GOOD_PLANE.project_direction(BAD_D),
    "plane.frame.plane": lambda: BAD_PLANE.frame(GOOD_P, GOOD_D),
    "plane.frame.origin": lambda: GOOD_PLANE.frame(BAD_P, GOOD_D),
    "plane.frame.tangent": lambda: GOOD_PLANE.frame(GOOD_P, BAD_D),
    "plane.winding_normal.plane": lambda: BAD_PLANE.winding_normal([GOOD_P, GOOD_P, GOOD_P]),
    "plane.winding_normal.points": lambda: GOOD_PLANE.winding_normal([GOOD_P, GOOD_P, BAD_P]),
    "line.through.anchor": lambda: Line.through(BAD_P, GOOD_D),
    "line.through.axis": lambda: Line.through(GOOD_P, BAD_D),
    "line.through_points.a": lambda: Line.through_points(BAD_P, GOOD_P),
    "line.through_points.b": lambda: Line.through_points(GOOD_P, BAD_P),
    "line.direction": lambda: BAD_LINE.direction(),
    "line.origin": lambda: BAD_LINE.origin(),
    "line.project.line": lambda: BAD_LINE.project(GOOD_P),
    "line.project.point": lambda: GOOD_LINE.project(BAD_P),
    "line.distance_to.line": lambda: BAD_LINE.distance_to(GOOD_P),
    "line.distance_to.point": lambda: GOOD_LINE.distance_to(BAD_P),
    "line.contains": lambda: BAD_LINE.contains(GOOD_P),
    "line.direction_along.line": lambda: BAD_LINE.direction_along([GOOD_P, GOOD_P]),
    "line.direction_along.points": lambda: GOOD_LINE.direction_along([GOOD_P, BAD_P]),
    "ray.through.origin": lambda: Ray.through(BAD_P, GOOD_D),
    "ray.through.direction": lambda: Ray.through(GOOD_P, BAD_D),
    "ray.from_to.origin": lambda: Ray.from_to(BAD_P, GOOD_P),
    "ray.from_to.target": lambda: Ray.from_to(GOOD_P, BAD_P),
    "ray.origin": lambda: BAD_RAY.origin(),
    "ray.direction": lambda: BAD_RAY.direction(),
    "ray.project.ray": lambda: BAD_RAY.project(GOOD_P),
    "ray.project.point": lambda: GOOD_RAY.project(BAD_P),
    "ray.distance_to.ray": lambda: BAD_RAY.distance_to(GOOD_P),
    "ray.distance_to.point": lambda: GOOD_RAY.distance_to(BAD_P),
    "ray.contains": lambda: BAD_RAY.contains(GOOD_P),
    "ray.point_at": lambda: BAD_RAY.point_at(1.0),
    "ray.reversed": lambda: BAD_RAY.reversed(),
    "segment.between.start": lambda: Segment.between(BAD_P, GOOD_P),
    "segment.between.end": lambda: Segment.between(GOOD_P, BAD_P),
    "segment.start": lambda: BAD_SEG.start(),
    "segment.end": lambda: BAD_SEG.end(),
    "segment.direction": lambda: BAD_SEG.direction(),
    "segment.length": lambda: BAD_SEG.length(),
    "segment.midpoint": lambda: BAD_SEG.midpoint(),
    "segment.project.segment": lambda: BAD_SEG.project(GOOD_P),
    "segment.project.point": lambda: GOOD_SEG.project(BAD_P),
    "segment.distance_to.segment": lambda: BAD_SEG.distance_to(GOOD_P),
    "segment.distance_to.point": lambda: GOOD_SEG.distance_to(BAD_P),
    "segment.contains": lambda: BAD_SEG.contains(GOOD_P),
    "segment.at": lambda: BAD_SEG.at(0.5),
    "segment.parameter_of.segment": lambda: BAD_SEG.parameter_of(GOOD_P),
    "segment.parameter_of.point": lambda: GOOD_SEG.parameter_of(BAD_P),
    "segment.reversed": lambda: BAD_SEG.reversed(),
    # duration
    "duration.sum.lhs": lambda: BAD_DUR + GOOD_DUR,
    "duration.sum.rhs": lambda: GOOD_DUR + BAD_DUR,
    "duration.sub": lambda: GOOD_DUR - BAD_DUR,
    "duration.scaled.dur": lambda: BAD_DUR.scale(GOOD_S),
    "duration.scaled.factor": lambda: GOOD_DUR.scale(BAD_S),
    "duration.ratio.num": lambda: BAD_DUR.ratio(GOOD_DUR),
    "duration.ratio.den": lambda: GOOD_DUR.ratio(BAD_DUR),
    "duration.abs": lambda: abs(BAD_DUR),
    "duration.min.lhs": lambda: BAD_DUR.min(GOOD_DUR),
    "duration.min.rhs": lambda: GOOD_DUR.min(BAD_DUR),
    "duration.max.lhs": lambda: BAD_DUR.max(GOOD_DUR),
    "duration.max.rhs": lambda: GOOD_DUR.max(BAD_DUR),
    "duration.clamp.v": lambda: BAD_DUR.clamp(GOOD_DUR, GOOD_DUR),
    "duration.clamp.lo": lambda: GOOD_DUR.clamp(BAD_DUR, GOOD_DUR),
    "duration.clamp.hi": lambda: GOOD_DUR.clamp(GOOD_DUR, BAD_DUR),
    "duration.lt.lhs": lambda: BAD_DUR.lt(GOOD_DUR),
    "duration.lt.rhs": lambda: GOOD_DUR.lt(BAD_DUR),
    "duration.le.lhs": lambda: BAD_DUR.le(GOOD_DUR),
    "duration.le.rhs": lambda: GOOD_DUR.le(BAD_DUR),
    "duration.gt.lhs": lambda: BAD_DUR.gt(GOOD_DUR),
    "duration.gt.rhs": lambda: GOOD_DUR.gt(BAD_DUR),
    "duration.ge.lhs": lambda: BAD_DUR.ge(GOOD_DUR),
    "duration.ge.rhs": lambda: GOOD_DUR.ge(BAD_DUR),
    # instant
    "instant.shifted.instant": lambda: BAD_I.shifted_by(GOOD_DUR),
    "instant.shifted.by": lambda: GOOD_I.shifted_by(BAD_DUR),
    "instant.diff.later": lambda: GOOD_I.duration_to(BAD_I),
    "instant.diff.earlier": lambda: BAD_I.duration_to(GOOD_I),
    "instant.lerp.a": lambda: BAD_I.lerp(GOOD_I, GOOD_S),
    "instant.lerp.b": lambda: GOOD_I.lerp(BAD_I, GOOD_S),
    "instant.lerp.t": lambda: GOOD_I.lerp(GOOD_I, BAD_S),
    "instant.min.lhs": lambda: BAD_I.min(GOOD_I),
    "instant.min.rhs": lambda: GOOD_I.min(BAD_I),
    "instant.max.lhs": lambda: BAD_I.max(GOOD_I),
    "instant.max.rhs": lambda: GOOD_I.max(BAD_I),
    "instant.centroid": lambda: Instant.centroid([GOOD_I, BAD_I]),
    "instant.affine.instant": lambda: Instant.affine([GOOD_I, BAD_I], [1, 1]),
    "instant.affine.weight": lambda: Instant.affine([GOOD_I, GOOD_I], [BAD_S, GOOD_S]),
    "instant.before.lhs": lambda: BAD_I.before(GOOD_I),
    "instant.before.rhs": lambda: GOOD_I.before(BAD_I),
    "instant.after.lhs": lambda: BAD_I.after(GOOD_I),
    "instant.after.rhs": lambda: GOOD_I.after(BAD_I),
    # interval
    "interval.between.start": lambda: Interval.between(BAD_I, GOOD_I),
    "interval.between.end": lambda: Interval.between(GOOD_I, BAD_I),
    "interval.start": lambda: BAD_INT.start(),
    "interval.end": lambda: BAD_INT.end(),
    "interval.duration": lambda: BAD_INT.duration(),
    "interval.lerp.interval": lambda: BAD_INT.lerp(GOOD_S),
    "interval.lerp.t": lambda: GOOD_INT.lerp(BAD_S),
    "interval.intersection.a": lambda: BAD_INT.intersection(GOOD_INT),
    "interval.intersection.b": lambda: GOOD_INT.intersection(BAD_INT),
    "interval.hull.a": lambda: BAD_INT.hull(GOOD_INT2),
    "interval.hull.b": lambda: GOOD_INT.hull(BAD_INT),
    "interval.clamp.interval": lambda: BAD_INT.clamp(GOOD_I),
    "interval.clamp.instant": lambda: GOOD_INT.clamp(BAD_I),
    "interval.shifted.interval": lambda: BAD_INT.shifted(GOOD_DUR),
    "interval.shifted.by": lambda: GOOD_INT.shifted(BAD_DUR),
    "interval.expanded.interval": lambda: BAD_INT.expanded(GOOD_DUR),
    "interval.expanded.by": lambda: GOOD_INT.expanded(BAD_DUR),
    "interval.contains.interval": lambda: BAD_INT.contains(GOOD_I),
    "interval.contains.instant": lambda: GOOD_INT.contains(BAD_I),
    "interval.overlaps.a": lambda: BAD_INT.overlaps(GOOD_INT2),
    "interval.overlaps.b": lambda: GOOD_INT.overlaps(BAD_INT),
    # coverage
    "coverage.of.member": lambda: Coverage.of([BAD_INT]),
    "coverage.union.a": lambda: BAD_COV.union(GOOD_COV),
    "coverage.union.b": lambda: GOOD_COV.union(BAD_COV),
    "coverage.intersection.a": lambda: BAD_COV.intersection(GOOD_COV2),
    "coverage.intersection.b": lambda: GOOD_COV.intersection(BAD_COV),
    "coverage.difference.a": lambda: BAD_COV.difference(GOOD_COV2),
    "coverage.difference.b": lambda: GOOD_COV.difference(BAD_COV),
    "coverage.contains.coverage": lambda: BAD_COV.contains(GOOD_I),
    "coverage.contains.instant": lambda: GOOD_COV.contains(BAD_I),
    "coverage.total_duration": lambda: BAD_COV.total_duration(),
    "coverage.hull": lambda: BAD_COV.hull(),
    "coverage.gaps": lambda: BAD_COV.gaps(),
    # timemap
    "timemap.shift": lambda: TimeMap.shift(BAD_DUR),
    "timemap.rate": lambda: TimeMap.rate(BAD_S),
    "timemap.affine.offset": lambda: TimeMap.affine(BAD_DUR, GOOD_S),
    "timemap.affine.rate": lambda: TimeMap.affine(GOOD_DUR, BAD_S),
    "timemap.compose.outer": lambda: BAD_TM @ GOOD_TM,
    "timemap.compose.inner": lambda: GOOD_TM @ BAD_TM,
    "timemap.inverse": lambda: BAD_TM.inverse(),
    "timemap.aligning.source": lambda: TimeMap.aligning(BAD_S, GOOD_S),
    "timemap.aligning.target": lambda: TimeMap.aligning(GOOD_S, BAD_S),
    "timemap.through.first.source": lambda: TimeMap.through((BAD_S, GOOD_S), (GOOD_S, GOOD_S)),
    "timemap.through.first.target": lambda: TimeMap.through((GOOD_S, BAD_S), (GOOD_S, GOOD_S)),
    "timemap.through.second.source": lambda: TimeMap.through((GOOD_S, GOOD_S), (BAD_S, GOOD_S)),
    "timemap.through.second.target": lambda: TimeMap.through((GOOD_S, GOOD_S), (GOOD_S, BAD_S)),
    # timewarp
    "timewarp.inverse": lambda: BAD_TW.inverse(),
    "timewarp.domain": lambda: BAD_TW.domain(),
    # timeline
    "timeline.derive.parent": lambda: BAD_TL.derive("x", GOOD_TM),
    "timeline.derive.by": lambda: GOOD_TL.derive("x", BAD_TM),
    "timeline.at.timeline": lambda: BAD_TL.at(GOOD_S),
    "timeline.at.local": lambda: GOOD_TL.at(BAD_S),
    "timeline.to_master": lambda: BAD_TL.to_master(),
    "timeline.relative_to.timeline": lambda: BAD_TL.relative_to(GOOD_TL),
    "timeline.relative_to.other": lambda: GOOD_TL.relative_to(BAD_TL),
    # sampling
    "sampling.uniform.interval": lambda: Sampling.uniform(BAD_INT, 3),
    "sampling.span": lambda: BAD_SAMP.span(),
    "sampling.count": lambda: BAD_SAMP.count(),
    "sampling.rate": lambda: BAD_SAMP.rate(),
    # scalar signal
    "signal.sampled.sampling": lambda: ScalarSignal.sampled(BAD_SAMP, [1.0]),
    "signal.at.signal": lambda: BAD_SIG.at(GOOD_I),
    "signal.at.instant": lambda: GOOD_SIG.at(BAD_I),
    "signal.over": lambda: BAD_SIG.over(),
    "signal.resample.source": lambda: BAD_SIG.resample(GOOD_SAMP),
    "signal.resample.onto": lambda: GOOD_SIG.resample(BAD_SAMP),
    "signal.reparam.source": lambda: BAD_SIG.reparameterize(GOOD_TM),
    "signal.reparam.by": lambda: GOOD_SIG.reparameterize(BAD_TM),
    "signal.reparam.warp.source": lambda: BAD_SIG.reparameterize(GOOD_TW),
    "signal.reparam.warp.by": lambda: GOOD_SIG.reparameterize(BAD_TW),
    "signal.restrict.source": lambda: BAD_SIG.restrict(GOOD_INT),
    "signal.restrict.to": lambda: GOOD_SIG.restrict(BAD_INT),
    "signal.shift.source": lambda: BAD_SIG.shift(GOOD_DUR),
    "signal.shift.by": lambda: GOOD_SIG.shift(BAD_DUR),
    "signal.defined_at.signal": lambda: BAD_SIG.defined_at(GOOD_I),
    "signal.defined_at.instant": lambda: GOOD_SIG.defined_at(BAD_I),
    "signal.add.lhs": lambda: BAD_SIG + GOOD_SIG,
    "signal.add.rhs": lambda: GOOD_SIG + BAD_SIG,
    "signal.sub.lhs": lambda: BAD_SIG - GOOD_SIG,
    "signal.sub.rhs": lambda: GOOD_SIG - BAD_SIG,
    "signal.mul.lhs": lambda: BAD_SIG * GOOD_SIG,
    "signal.mul.rhs": lambda: GOOD_SIG * BAD_SIG,
    "signal.div.lhs": lambda: BAD_SIG / GOOD_SIG,
    "signal.div.rhs": lambda: GOOD_SIG / BAD_SIG,
    # vec3 signal
    "vsignal.sampled.sampling": lambda: Vec3Signal.sampled(BAD_SAMP, [[1.0, 0.0, 0.0]]),
    "vsignal.at.signal": lambda: BAD_VSIG.at(GOOD_I),
    "vsignal.at.instant": lambda: GOOD_VSIG.at(BAD_I),
    "vsignal.over": lambda: BAD_VSIG.over(),
    "vsignal.resample.source": lambda: BAD_VSIG.resample(GOOD_SAMP),
    "vsignal.resample.onto": lambda: GOOD_VSIG.resample(BAD_SAMP),
    "vsignal.reparam.source": lambda: BAD_VSIG.reparameterize(GOOD_TM),
    "vsignal.reparam.by": lambda: GOOD_VSIG.reparameterize(BAD_TM),
    "vsignal.restrict.source": lambda: BAD_VSIG.restrict(GOOD_INT),
    "vsignal.restrict.to": lambda: GOOD_VSIG.restrict(BAD_INT),
    "vsignal.shift.source": lambda: BAD_VSIG.shift(GOOD_DUR),
    "vsignal.shift.by": lambda: GOOD_VSIG.shift(BAD_DUR),
    "vsignal.defined_at.signal": lambda: BAD_VSIG.defined_at(GOOD_I),
    "vsignal.defined_at.instant": lambda: GOOD_VSIG.defined_at(BAD_I),
    "vsignal.add.lhs": lambda: BAD_VSIG + GOOD_VSIG,
    "vsignal.add.rhs": lambda: GOOD_VSIG + BAD_VSIG,
    "vsignal.sub.lhs": lambda: BAD_VSIG - GOOD_VSIG,
    "vsignal.sub.rhs": lambda: GOOD_VSIG - BAD_VSIG,
    "vsignal.dot.lhs": lambda: BAD_VSIG.dot(GOOD_VSIG),
    "vsignal.dot.rhs": lambda: GOOD_VSIG.dot(BAD_VSIG),
    # direction3 signal (the manifold case)
    "dsignal.sampled.sampling": lambda: Direction3Signal.sampled(BAD_SAMP, [[1.0, 0.0, 0.0]]),
    "dsignal.at.signal": lambda: BAD_DSIG.at(GOOD_I),
    "dsignal.at.instant": lambda: GOOD_DSIG.at(BAD_I),
    "dsignal.over": lambda: BAD_DSIG.over(),
    "dsignal.resample.source": lambda: BAD_DSIG.resample(GOOD_SAMP),
    "dsignal.resample.onto": lambda: GOOD_DSIG.resample(BAD_SAMP),
    "dsignal.reparam.source": lambda: BAD_DSIG.reparameterize(GOOD_TM),
    "dsignal.reparam.by": lambda: GOOD_DSIG.reparameterize(BAD_TM),
    "dsignal.restrict.source": lambda: BAD_DSIG.restrict(GOOD_INT),
    "dsignal.restrict.to": lambda: GOOD_DSIG.restrict(BAD_INT),
    "dsignal.shift.source": lambda: BAD_DSIG.shift(GOOD_DUR),
    "dsignal.shift.by": lambda: GOOD_DSIG.shift(BAD_DUR),
    "dsignal.defined_at.signal": lambda: BAD_DSIG.defined_at(GOOD_I),
    "dsignal.defined_at.instant": lambda: GOOD_DSIG.defined_at(BAD_I),
    # transform signal (SE(3))
    "tsignal.sampled.sampling": lambda: TransformSignal.sampled(BAD_SAMP, [_ID]),
    "tsignal.at.signal": lambda: BAD_TSIG.at(GOOD_I),
    "tsignal.at.instant": lambda: GOOD_TSIG.at(BAD_I),
    "tsignal.over": lambda: BAD_TSIG.over(),
    "tsignal.resample.source": lambda: BAD_TSIG.resample(GOOD_SAMP),
    "tsignal.resample.onto": lambda: GOOD_TSIG.resample(BAD_SAMP),
    "tsignal.reparam.source": lambda: BAD_TSIG.reparameterize(GOOD_TM),
    "tsignal.reparam.by": lambda: GOOD_TSIG.reparameterize(BAD_TM),
    "tsignal.restrict.source": lambda: BAD_TSIG.restrict(GOOD_INT),
    "tsignal.restrict.to": lambda: GOOD_TSIG.restrict(BAD_INT),
    "tsignal.shift.source": lambda: BAD_TSIG.shift(GOOD_DUR),
    "tsignal.shift.by": lambda: GOOD_TSIG.shift(BAD_DUR),
    "tsignal.defined_at.signal": lambda: BAD_TSIG.defined_at(GOOD_I),
    "tsignal.defined_at.instant": lambda: GOOD_TSIG.defined_at(BAD_I),
    # point3 signal (framed; grounding partiality)
    "psignal.at.signal": lambda: BAD_PSIG.at(GOOD_I),
    "psignal.at.instant": lambda: GOOD_PSIG.at(BAD_I),
    "psignal.over": lambda: BAD_PSIG.over(),
    "psignal.resample.source": lambda: BAD_PSIG.resample(GOOD_SAMP),
    "psignal.resample.onto": lambda: GOOD_PSIG.resample(BAD_SAMP),
    "psignal.reparam.source": lambda: BAD_PSIG.reparameterize(GOOD_TM),
    "psignal.reparam.by": lambda: GOOD_PSIG.reparameterize(BAD_TM),
    "psignal.restrict.source": lambda: BAD_PSIG.restrict(GOOD_INT),
    "psignal.restrict.to": lambda: GOOD_PSIG.restrict(BAD_INT),
    "psignal.shift.source": lambda: BAD_PSIG.shift(GOOD_DUR),
    "psignal.shift.by": lambda: GOOD_PSIG.shift(BAD_DUR),
    "psignal.defined_at.signal": lambda: BAD_PSIG.defined_at(GOOD_I),
    "psignal.defined_at.instant": lambda: GOOD_PSIG.defined_at(BAD_I),
    "psignal.displacement.lhs": lambda: BAD_PSIG.displacement_to(GOOD_PSIG),
    "psignal.displacement.rhs": lambda: GOOD_PSIG.displacement_to(BAD_PSIG),
    "psignal.distance.lhs": lambda: BAD_PSIG.distance_to(GOOD_PSIG),
    "psignal.distance.rhs": lambda: GOOD_PSIG.distance_to(BAD_PSIG),
    # point3 bundle
    "bundle.of": lambda: Point3Bundle.of([BAD_P]),
    "bundle.at": lambda: BAD_BUNDLE.at(0),
    "bundle.present": lambda: BAD_BUNDLE.present(0),
    "bundle.count": lambda: BAD_BUNDLE.count(),
    "bundle.where": lambda: BAD_BUNDLE.where([0]),
    "bundle.centroid": lambda: BAD_BUNDLE.centroid(),
    "bundle.fit_plane": lambda: BAD_BUNDLE.fit_plane(),
    "bundle.fit_line": lambda: BAD_BUNDLE.fit_line(),
    # other bundle facades
    "vbundle.of": lambda: Vec3Bundle.of([BAD_V3]),
    "vbundle.at": lambda: BAD_VB.at(0),
    "vbundle.where": lambda: BAD_VB.where([0]),
    "vbundle.mean": lambda: BAD_VB.mean(),
    "sbundle.of": lambda: ScalarBundle.of([BAD_S]),
    "sbundle.at": lambda: BAD_SB.at(0),
    "sbundle.where": lambda: BAD_SB.where([0]),
    "sbundle.mean": lambda: BAD_SB.mean(),
    "dbundle.of": lambda: Direction3Bundle.of([BAD_D]),
    "dbundle.at": lambda: BAD_DB.at(0),
    "dbundle.where": lambda: BAD_DB.where([0]),
    "dbundle.mean": lambda: BAD_DB.mean(),
    "tbundle.of": lambda: TransformBundle.of([BAD_T]),
    "tbundle.at": lambda: BAD_TB.at(0),
    "tbundle.where": lambda: BAD_TB.where([0]),
    # bundle algebra — zip (lift), folds, broadcast
    "sbundle.add.lhs": lambda: BAD_SB + GOOD_SB,
    "sbundle.add.rhs": lambda: GOOD_SB + BAD_SB,
    "sbundle.sub.lhs": lambda: BAD_SB - GOOD_SB,
    "sbundle.sub.rhs": lambda: GOOD_SB - BAD_SB,
    "sbundle.mul.lhs": lambda: BAD_SB * GOOD_SB,
    "sbundle.mul.rhs": lambda: GOOD_SB * BAD_SB,
    "sbundle.div.num": lambda: BAD_SB / GOOD_SB,
    "sbundle.div.den": lambda: GOOD_SB / BAD_SB,
    "sbundle.sum": lambda: BAD_SB.sum(),
    "vbundle.add.lhs": lambda: BAD_VB + GOOD_VB,
    "vbundle.add.rhs": lambda: GOOD_VB + BAD_VB,
    "vbundle.sub.lhs": lambda: BAD_VB - GOOD_VB,
    "vbundle.sub.rhs": lambda: GOOD_VB - BAD_VB,
    "vbundle.dot.lhs": lambda: BAD_VB.dot(GOOD_VB),
    "vbundle.dot.rhs": lambda: GOOD_VB.dot(BAD_VB),
    "vbundle.sum": lambda: BAD_VB.sum(),
    "pbundle.displacement.lhs": lambda: BAD_BUNDLE.displacement_to(GOOD_PB),
    "pbundle.displacement.rhs": lambda: GOOD_PB.displacement_to(BAD_BUNDLE),
    "pbundle.distance.lhs": lambda: BAD_BUNDLE.distance_to(GOOD_PB),
    "pbundle.distance.rhs": lambda: GOOD_PB.distance_to(BAD_BUNDLE),
    "pbundle.transformed_by.source": lambda: BAD_BUNDLE.transformed_by(GOOD_T),
    "pbundle.transformed_by.transform": lambda: GOOD_PB.transformed_by(BAD_T),
    # point3 bundle signal (collection over time)
    "pbsignal.from_frames.sampling": lambda: Point3BundleSignal.from_frames([1, 0], [[[0, 0, 0]], [[1, 0, 0]]]),
    "pbsignal.at.signal": lambda: BAD_PBS.at(GOOD_I),
    "pbsignal.at.instant": lambda: GOOD_PBS.at(BAD_I),
    "pbsignal.key.source": lambda: BAD_PBS.key(0),
    "pbsignal.over": lambda: BAD_PBS.over(),
    "pbsignal.resample.source": lambda: BAD_PBS.resample(GOOD_SAMP),
    "pbsignal.resample.onto": lambda: GOOD_PBS.resample(BAD_SAMP),
    "pbsignal.reparam.source": lambda: BAD_PBS.reparameterize(GOOD_TM),
    "pbsignal.reparam.by": lambda: GOOD_PBS.reparameterize(BAD_TM),
    "pbsignal.reparam.warp": lambda: GOOD_PBS.reparameterize(BAD_TW),
    "pbsignal.restrict.source": lambda: BAD_PBS.restrict(GOOD_INT),
    "pbsignal.restrict.to": lambda: GOOD_PBS.restrict(BAD_INT),
    "pbsignal.shift.source": lambda: BAD_PBS.shift(GOOD_DUR),
    "pbsignal.shift.by": lambda: GOOD_PBS.shift(BAD_DUR),
}


@pytest.mark.parametrize("thunk", CASES.values(), ids=list(CASES))
def test_unresolvability_propagates(thunk: Callable[[], object]) -> None:
    assert isinstance(thunk().decide(), Unresolvable)  # type: ignore[attr-defined]
