"""Unresolvability propagates through every combinator, in every input position.

This is the core promise of the decidability design: anything built on an
unanswerable sub-expression is itself unanswerable, with the reason intact. We
exercise each combinator with an ``Unresolvable`` input in each position so the
propagation branches are all covered.
"""

from __future__ import annotations

from collections.abc import Callable

import pytest

from fungeom import (
    CoordinateFrame,
    Coverage,
    Direction2,
    Direction3,
    Direction3Signal,
    Duration,
    Frame,
    Frame2,
    Instant,
    Interval,
    BoolBundle,
    Direction3Bundle,
    Face,
    FaceSignal,
    Line,
    Line2,
    Plane,
    PlaneSignal,
    PlaneValue,
    Point2,
    Point2Bundle,
    ScalarBundleSignal,
    Point3,
    Point3Bundle,
    Point3BundleSignal,
    Point3Signal,
    Ray,
    Ray2,
    Region2,
    Roster,
    RosterMap,
    ScalarBundle,
    Segment,
    Segment2,
    TransformBundle,
    TransformBundleSignal,
    Vec3Bundle,
    RigidTransform,
    Sampling,
    Scalar,
    ScalarSignal,
    TimeMap,
    TimeWarp,
    Timeline,
    Transform,
    Transform2,
    TransformSignal,
    Unresolvable,
    Vec2,
    Vec3,
    Vec3Signal,
)

# One Unresolvable and one Resolvable resolver of each type.
BAD_S, GOOD_S = Scalar.of(1) / Scalar.of(0), Scalar.of(2)
BAD_V3, GOOD_V3 = Vec3.of(0, 0, 0).normalized(), Vec3.of(1, 0, 0)
BAD_V2, GOOD_V2 = Vec2.of(0, 0).normalized(), Vec2.of(1, 0)
BAD_T, GOOD_T = Transform.rotation(Vec3.of(0, 0, 0), Scalar.of(1)), Transform.identity()
BAD_D, GOOD_D = Direction3.of(0, 0, 0), Direction3.of(1, 0, 0)
BAD_D2, GOOD_D2 = Direction2.of(0, 0), Direction2.of(1, 0)
BAD_T2, GOOD_T2 = Transform2.rotation(BAD_S), Transform2.identity()
BAD_F2, GOOD_F2 = Frame2.detached("loose2"), Frame2.world
BAD_P2 = Point2.at(0, 0, frame=Frame2.detached("loose2p"))
GOOD_P2 = Point2.at(0, 0)
BAD_L2 = Line2.through(BAD_P2, GOOD_D2)
GOOD_L2 = Line2.through(GOOD_P2, GOOD_D2)
BAD_R2 = Ray2.through(BAD_P2, GOOD_D2)
GOOD_R2 = Ray2.through(GOOD_P2, GOOD_D2)
BAD_SEG2 = Segment2.between(BAD_P2, GOOD_P2)
GOOD_SEG2 = Segment2.between(GOOD_P2, Point2.at(1, 0))
BAD_F, GOOD_F = Frame.detached("loose"), Frame.world
BAD_P = Point3.at(0, 0, 0, frame=CoordinateFrame.detached("loose"))
GOOD_P = Point3.at(0, 0, 0)
BAD_PLANE = Plane.through(BAD_P, GOOD_D)
GOOD_PLANE = Plane.through(GOOD_P, GOOD_D)
BAD_LINE = Line.through(BAD_P, GOOD_D)
GOOD_LINE = Line.through(GOOD_P, GOOD_D)
BAD_RAY = Ray.through(BAD_P, GOOD_D)
GOOD_RAY = Ray.through(GOOD_P, GOOD_D)
BAD_SEG = Segment.between(BAD_P, GOOD_P)
GOOD_SEG = Segment.between(GOOD_P, Point3.at(1, 0, 0))
BAD_DUR, GOOD_DUR = Duration.of(1).scale(BAD_S), Duration.of(2)
BAD_I, GOOD_I = Instant.epoch.shifted_by(BAD_DUR), Instant.at(0)
BAD_INT = Interval.between(BAD_I, GOOD_I)
GOOD_INT, GOOD_INT2 = Interval.between(Instant.at(0), Instant.at(10)), Interval.between(Instant.at(5), Instant.at(20))
BAD_COV = Coverage.of([BAD_INT])
BAD_TM, GOOD_TM = TimeMap.rate(0).inverse(), TimeMap.identity()
BAD_TW = TimeWarp.through([(1.0, 0.0), (0.0, 1.0)])  # non-monotonic source knots
GOOD_TW = TimeWarp.through([(0.0, 0.0), (2.0, 2.0)])
BAD_TL, GOOD_TL = Timeline.detached("loose"), Timeline.master
BAD_SAMP, GOOD_SAMP = Sampling.at_times([1, 0]), Sampling.at_times([0, 1])
BAD_SIG = ScalarSignal.from_samples([1, 0], [1, 2])
GOOD_SIG = ScalarSignal.from_samples([0, 1, 2], [10, 20, 30])
BAD_BOOLSIG, GOOD_BOOLSIG = BAD_SIG.lt(15.0), GOOD_SIG.lt(15.0)
BAD_BUNDLE, GOOD_PB = Point3Bundle.of([BAD_P]), Point3Bundle.of([GOOD_P])
BAD_P2B, GOOD_P2B = Point2Bundle.of([BAD_P2]), Point2Bundle.of([GOOD_P2])
BAD_REGION = Region2.polygon([BAD_P2, GOOD_P2, Point2.at(1, 0)])
GOOD_REGION = Region2.rectangle(2, 2)
BAD_FACE = Face.on(BAD_PLANE, GOOD_REGION)
GOOD_FACE = Face.on(GOOD_PLANE, GOOD_REGION)
BAD_PBS = Point3BundleSignal.from_frames([1, 0], [[[0, 0, 0]], [[1, 0, 0]]])  # out-of-order sampling
GOOD_PBS = Point3BundleSignal.from_frames([0, 1], [[[0, 0, 0]], [[1, 0, 0]]])
BAD_VB, GOOD_VB = Vec3Bundle.of([BAD_V3]), Vec3Bundle.of([GOOD_V3])
BAD_SB, GOOD_SB = ScalarBundle.of([BAD_S]), ScalarBundle.of([GOOD_S])
BAD_DB, GOOD_DB = Direction3Bundle.of([BAD_D]), Direction3Bundle.of([GOOD_D])
BAD_TB, GOOD_TB = TransformBundle.of([BAD_T]), TransformBundle.of([GOOD_T])
BAD_TBS = TransformBundleSignal.from_frames([1, 0], [[GOOD_T], [GOOD_T]])  # out-of-order sampling
GOOD_TBS = TransformBundleSignal.from_frames([0, 1], [[GOOD_T], [GOOD_T]])
# roster / rostermap (rung 3) — Unresolvable only by propagation, seeded from an unbuildable bundle's support
BAD_ROSTER, GOOD_ROSTER = BAD_BUNDLE.support(), Roster.of([0])
BAD_RMAP, GOOD_RMAP = RosterMap.identity(BAD_ROSTER), RosterMap.of({0: "a"})
BAD_VSIG = Vec3Signal.from_samples([1, 0], [[0, 0, 0], [1, 1, 1]])
GOOD_VSIG = Vec3Signal.from_samples([0, 1, 2], [[0, 0, 0], [1, 0, 0], [2, 0, 0]])
BAD_DSIG = Direction3Signal.from_samples([1, 0], [[1, 0, 0], [0, 1, 0]])
GOOD_DSIG = Direction3Signal.from_samples([0, 1, 2], [[1, 0, 0], [0, 1, 0], [0, 0, 1]])
_ID = RigidTransform.identity()
BAD_TSIG = TransformSignal.from_samples([1, 0], [_ID, _ID])
GOOD_TSIG = TransformSignal.from_samples([0, 1, 2], [_ID, _ID, _ID])
BAD_PSIG = Point3Signal.from_samples([1, 0], [[0, 0, 0], [1, 1, 1]])
GOOD_PSIG = Point3Signal.from_samples([0, 1, 2], [[0, 0, 0], [1, 0, 0], [2, 0, 0]])
BAD_FSIG = FaceSignal.of(GOOD_FACE, BAD_TSIG)  # a moving patch with a bad pose
GOOD_FSIG = FaceSignal.of(GOOD_FACE, GOOD_TSIG)
_PLN = PlaneValue(point=[0, 0, 0], normal=[0, 0, 1])
BAD_PLSIG = PlaneSignal.from_samples([1, 0], [_PLN, _PLN])  # out-of-order sampling
GOOD_PLSIG = PlaneSignal.from_samples([0, 1], [_PLN, _PLN])
BAD_SBS = ScalarBundleSignal.from_frames([1, 0], [[1.0], [2.0]])  # out-of-order sampling
GOOD_SBS = ScalarBundleSignal.from_frames([0, 1], [[1.0], [2.0]])
GOOD_COV, GOOD_COV2 = Coverage.of([GOOD_INT]), Coverage.of([GOOD_INT2])
BAD_BOOL, GOOD_BOOL = BAD_S.lt(GOOD_S), GOOD_S.lt(Scalar.of(3))
BAD_BB, GOOD_BB = BoolBundle.of([BAD_BOOL]), BoolBundle.of([GOOD_BOOL])

CASES: dict[str, Callable[[], object]] = {
    # scalar (both positions for binaries)
    "scalar.add.lhs": lambda: BAD_S + GOOD_S,
    "scalar.add.rhs": lambda: GOOD_S + BAD_S,
    "scalar.sub": lambda: GOOD_S - BAD_S,
    "scalar.mul.lhs": lambda: BAD_S * GOOD_S,
    "scalar.mul.rhs": lambda: GOOD_S * BAD_S,
    "scalar.div.num": lambda: BAD_S / GOOD_S,
    "scalar.div.den": lambda: GOOD_S / BAD_S,
    "scalar.min.lhs": lambda: BAD_S.min(GOOD_S),
    "scalar.min.rhs": lambda: GOOD_S.min(BAD_S),
    "scalar.max.lhs": lambda: BAD_S.max(GOOD_S),
    "scalar.max.rhs": lambda: GOOD_S.max(BAD_S),
    "scalar.pow.base": lambda: BAD_S**GOOD_S,
    "scalar.pow.exp": lambda: GOOD_S**BAD_S,
    "scalar.clamp.v": lambda: BAD_S.clamp(GOOD_S, GOOD_S),
    "scalar.clamp.lo": lambda: GOOD_S.clamp(BAD_S, GOOD_S),
    "scalar.clamp.hi": lambda: GOOD_S.clamp(GOOD_S, BAD_S),
    "scalar.abs": lambda: abs(BAD_S),
    "scalar.sqrt": lambda: BAD_S.sqrt(),
    "scalar.sign": lambda: BAD_S.sign(),
    "scalar.floor": lambda: BAD_S.floor(),
    "scalar.ceil": lambda: BAD_S.ceil(),
    "scalar.round": lambda: BAD_S.round(),
    "scalar.mod.lhs": lambda: BAD_S.mod(GOOD_S),
    "scalar.mod.rhs": lambda: GOOD_S.mod(BAD_S),
    "scalar.lt.lhs": lambda: BAD_S.lt(GOOD_S),
    "scalar.lt.rhs": lambda: GOOD_S.lt(BAD_S),
    "scalar.le.lhs": lambda: BAD_S.le(GOOD_S),
    "scalar.le.rhs": lambda: GOOD_S.le(BAD_S),
    "scalar.gt.lhs": lambda: BAD_S.gt(GOOD_S),
    "scalar.gt.rhs": lambda: GOOD_S.gt(BAD_S),
    "scalar.ge.lhs": lambda: BAD_S.ge(GOOD_S),
    "scalar.ge.rhs": lambda: GOOD_S.ge(BAD_S),
    # bool (logical algebra; strict propagation)
    "bool.and.lhs": lambda: BAD_BOOL.and_(GOOD_BOOL),
    "bool.and.rhs": lambda: GOOD_BOOL.and_(BAD_BOOL),
    "bool.or.lhs": lambda: BAD_BOOL.or_(GOOD_BOOL),
    "bool.or.rhs": lambda: GOOD_BOOL.or_(BAD_BOOL),
    "bool.not": lambda: BAD_BOOL.not_(),
    # vec3
    "vec3.add.lhs": lambda: BAD_V3 + GOOD_V3,
    "vec3.add.rhs": lambda: GOOD_V3 + BAD_V3,
    "vec3.scale.vec": lambda: BAD_V3.scale(GOOD_S),
    "vec3.scale.factor": lambda: GOOD_V3.scale(BAD_S),
    "vec3.dot.lhs": lambda: BAD_V3.dot(GOOD_V3),
    "vec3.dot.rhs": lambda: GOOD_V3.dot(BAD_V3),
    "vec3.cross.lhs": lambda: BAD_V3.cross(GOOD_V3),
    "vec3.cross.rhs": lambda: GOOD_V3.cross(BAD_V3),
    "vec3.scalar_triple.a": lambda: BAD_V3.scalar_triple(GOOD_V3, GOOD_V3),
    "vec3.scalar_triple.b": lambda: GOOD_V3.scalar_triple(BAD_V3, GOOD_V3),
    "vec3.scalar_triple.c": lambda: GOOD_V3.scalar_triple(GOOD_V3, BAD_V3),
    "vec3.lerp.a": lambda: BAD_V3.lerp(GOOD_V3, GOOD_S),
    "vec3.lerp.b": lambda: GOOD_V3.lerp(BAD_V3, GOOD_S),
    "vec3.lerp.t": lambda: GOOD_V3.lerp(GOOD_V3, BAD_S),
    "vec3.proj.a": lambda: BAD_V3.project_onto(GOOD_V3),
    "vec3.proj.onto": lambda: GOOD_V3.project_onto(BAD_V3),
    "vec3.rej.a": lambda: BAD_V3.reject_from(GOOD_V3),
    "vec3.rej.onto": lambda: GOOD_V3.reject_from(BAD_V3),
    "vec3.norm": lambda: BAD_V3.norm(),
    "vec3.normalized": lambda: BAD_V3.normalized(),
    "vec3.coord": lambda: BAD_V3.x(),
    "vec3.angle.lhs": lambda: BAD_V3.angle_to(GOOD_V3),
    "vec3.angle.rhs": lambda: GOOD_V3.angle_to(BAD_V3),
    "vec3.with_norm.vec": lambda: BAD_V3.with_norm(GOOD_S),
    "vec3.with_norm.len": lambda: GOOD_V3.with_norm(BAD_S),
    # vec2
    "vec2.add.lhs": lambda: BAD_V2 + GOOD_V2,
    "vec2.add.rhs": lambda: GOOD_V2 + BAD_V2,
    "vec2.scale.vec": lambda: BAD_V2.scale(GOOD_S),
    "vec2.scale.factor": lambda: GOOD_V2.scale(BAD_S),
    "vec2.dot.lhs": lambda: BAD_V2.dot(GOOD_V2),
    "vec2.dot.rhs": lambda: GOOD_V2.dot(BAD_V2),
    "vec2.cross.lhs": lambda: BAD_V2.cross(GOOD_V2),
    "vec2.cross.rhs": lambda: GOOD_V2.cross(BAD_V2),
    "vec2.lerp.a": lambda: BAD_V2.lerp(GOOD_V2, GOOD_S),
    "vec2.lerp.b": lambda: GOOD_V2.lerp(BAD_V2, GOOD_S),
    "vec2.lerp.t": lambda: GOOD_V2.lerp(GOOD_V2, BAD_S),
    "vec2.proj.a": lambda: BAD_V2.project_onto(GOOD_V2),
    "vec2.proj.onto": lambda: GOOD_V2.project_onto(BAD_V2),
    "vec2.rej.a": lambda: BAD_V2.reject_from(GOOD_V2),
    "vec2.rej.onto": lambda: GOOD_V2.reject_from(BAD_V2),
    "vec2.components": lambda: Vec2.of(BAD_S, GOOD_S),
    "vec2.norm": lambda: BAD_V2.norm(),
    "vec2.normalized": lambda: BAD_V2.normalized(),
    "vec2.coord": lambda: BAD_V2.x(),
    "vec2.angle.lhs": lambda: BAD_V2.angle_to(GOOD_V2),
    "vec2.angle.rhs": lambda: GOOD_V2.angle_to(BAD_V2),
    "vec2.with_norm.vec": lambda: BAD_V2.with_norm(GOOD_S),
    "vec2.with_norm.len": lambda: GOOD_V2.with_norm(BAD_S),
    "vec2.perpendicular": lambda: BAD_V2.perpendicular(),
    # transform
    "tf.compose.a": lambda: BAD_T @ GOOD_T,
    "tf.compose.b": lambda: GOOD_T @ BAD_T,
    "tf.inverse": lambda: BAD_T.inverse(),
    "tf.slerp.a": lambda: BAD_T.slerp(GOOD_T, GOOD_S),
    "tf.slerp.b": lambda: GOOD_T.slerp(BAD_T, GOOD_S),
    "tf.slerp.t": lambda: GOOD_T.slerp(GOOD_T, BAD_S),
    "tf.rotation.axis": lambda: Transform.rotation(BAD_V3, GOOD_S),
    "tf.rotation.angle": lambda: Transform.rotation(GOOD_V3, BAD_S),
    "tf.translation": lambda: Transform.translation(BAD_V3),
    "tf.apply_vec.tf": lambda: BAD_T.transform_vector(GOOD_V3),
    "tf.apply_vec.vec": lambda: GOOD_T.transform_vector(BAD_V3),
    "tf.apply_dir.tf": lambda: BAD_T.transform_direction(GOOD_D),
    "tf.apply_dir.dir": lambda: GOOD_T.transform_direction(BAD_D),
    "tf.translation_part": lambda: BAD_T.translation_part(),
    "tf.rotation_part": lambda: BAD_T.rotation_part(),
    "tf.aligning.source": lambda: Transform.aligning(BAD_D, GOOD_D),
    "tf.aligning.target": lambda: Transform.aligning(GOOD_D, BAD_D),
    "tf.from_axes.x": lambda: Transform.from_axes(BAD_D, GOOD_D),
    "tf.from_axes.y": lambda: Transform.from_axes(GOOD_D, BAD_D),
    "tf.from_axes.origin": lambda: Transform.from_axes(GOOD_D, Direction3.of(0, 1, 0), origin=BAD_V3),
    "tf.look_at.eye": lambda: Transform.look_at(BAD_V3, GOOD_V3, up=GOOD_D),
    "tf.look_at.target": lambda: Transform.look_at(GOOD_V3, BAD_V3, up=GOOD_D),
    "tf.look_at.up": lambda: Transform.look_at(GOOD_V3, Vec3.of(0, 0, 1), up=BAD_D),
    # direction
    "dir.reversed": lambda: BAD_D.reversed(),
    "dir.angle.lhs": lambda: BAD_D.angle_to(GOOD_D),
    "dir.angle.rhs": lambda: GOOD_D.angle_to(BAD_D),
    "dir.slerp.a": lambda: BAD_D.slerp(GOOD_D, GOOD_S),
    "dir.slerp.b": lambda: GOOD_D.slerp(BAD_D, GOOD_S),
    "dir.slerp.t": lambda: GOOD_D.slerp(GOOD_D, BAD_S),
    "dir.as_vector": lambda: BAD_D.as_vector(),
    "dir.towards": lambda: Direction3.towards(BAD_V3),
    "dir.dot.lhs": lambda: BAD_D.dot(GOOD_D),
    "dir.dot.rhs": lambda: GOOD_D.dot(BAD_D),
    "dir.cross.lhs": lambda: BAD_D.cross(GOOD_D),
    "dir.cross.rhs": lambda: GOOD_D.cross(BAD_D),
    "dir.any_perpendicular": lambda: BAD_D.any_perpendicular(),
    "dir.signed_angle.source": lambda: BAD_D.signed_angle_to(Direction3.of(1, 0, 0), about=Direction3.of(0, 0, 1)),
    "dir.signed_angle.target": lambda: Direction3.of(1, 0, 0).signed_angle_to(BAD_D, about=Direction3.of(0, 0, 1)),
    "dir.signed_angle.about": lambda: Direction3.of(1, 0, 0).signed_angle_to(Direction3.of(0, 1, 0), about=BAD_D),
    "dir2.of.scalar": lambda: Direction2.of(BAD_S, GOOD_S),
    "dir2.towards": lambda: Direction2.towards(BAD_V2),
    "dir2.reversed": lambda: BAD_D2.reversed(),
    "dir2.perpendicular": lambda: BAD_D2.perpendicular(),
    "dir2.angle": lambda: BAD_D2.angle(),
    "dir2.angle_to.lhs": lambda: BAD_D2.angle_to(GOOD_D2),
    "dir2.angle_to.rhs": lambda: GOOD_D2.angle_to(BAD_D2),
    "dir2.signed_angle.lhs": lambda: BAD_D2.signed_angle_to(GOOD_D2),
    "dir2.signed_angle.rhs": lambda: GOOD_D2.signed_angle_to(BAD_D2),
    "dir2.slerp.a": lambda: BAD_D2.slerp(GOOD_D2, GOOD_S),
    "dir2.slerp.b": lambda: GOOD_D2.slerp(BAD_D2, GOOD_S),
    "dir2.slerp.t": lambda: GOOD_D2.slerp(GOOD_D2, BAD_S),
    "dir2.dot.lhs": lambda: BAD_D2.dot(GOOD_D2),
    "dir2.dot.rhs": lambda: GOOD_D2.dot(BAD_D2),
    "dir2.as_vector": lambda: BAD_D2.as_vector(),
    "tf2.translation": lambda: Transform2.translation(BAD_V2),
    "tf2.rotation.angle": lambda: Transform2.rotation(BAD_S),
    "tf2.compose.a": lambda: BAD_T2 @ GOOD_T2,
    "tf2.compose.b": lambda: GOOD_T2 @ BAD_T2,
    "tf2.inverse": lambda: BAD_T2.inverse(),
    "tf2.slerp.a": lambda: BAD_T2.slerp(GOOD_T2, GOOD_S),
    "tf2.slerp.b": lambda: GOOD_T2.slerp(BAD_T2, GOOD_S),
    "tf2.slerp.t": lambda: GOOD_T2.slerp(GOOD_T2, BAD_S),
    "tf2.apply_vec.tf": lambda: BAD_T2.transform_vector(GOOD_V2),
    "tf2.apply_vec.vec": lambda: GOOD_T2.transform_vector(BAD_V2),
    "tf2.apply_dir.tf": lambda: BAD_T2.transform_direction(GOOD_D2),
    "tf2.apply_dir.dir": lambda: GOOD_T2.transform_direction(BAD_D2),
    "tf2.translation_part": lambda: BAD_T2.translation_part(),
    "tf2.rotation_part": lambda: BAD_T2.rotation_part(),
    "tf2.angle": lambda: BAD_T2.angle(),
    # frame
    "frame.attach.parent": lambda: BAD_F.attach("x", GOOD_T),
    "frame.attach.transform": lambda: GOOD_F.attach("x", BAD_T),
    "frame.relative.frame": lambda: BAD_F.relative_to(GOOD_F),
    "frame.relative.other": lambda: GOOD_F.relative_to(BAD_F),
    "frame2.attach.parent": lambda: BAD_F2.attach("x", GOOD_T2),
    "frame2.attach.transform": lambda: GOOD_F2.attach("x", BAD_T2),
    "frame2.relative.frame": lambda: BAD_F2.relative_to(GOOD_F2),
    "frame2.relative.other": lambda: GOOD_F2.relative_to(BAD_F2),
    "pt2.in_frame.local": lambda: Point2.in_frame(BAD_V2, GOOD_F2),
    "pt2.in_frame.frame": lambda: Point2.in_frame(GOOD_V2, BAD_F2),
    "pt2.coordinates_in.point": lambda: BAD_P2.coordinates_in(GOOD_F2),
    "pt2.coordinates_in.frame": lambda: GOOD_P2.coordinates_in(BAD_F2),
    "pt2.centroid": lambda: Point2.centroid([GOOD_P2, BAD_P2]),
    "pt2.affine.point": lambda: Point2.affine([GOOD_P2, BAD_P2], [1, 1]),
    "pt2.affine.weight": lambda: Point2.affine([GOOD_P2, GOOD_P2], [BAD_S, GOOD_S]),
    "pt2.translate.point": lambda: BAD_P2.translate(GOOD_V2),
    "pt2.translate.offset": lambda: GOOD_P2.translate(BAD_V2),
    "pt2.lerp.a": lambda: BAD_P2.lerp(GOOD_P2, GOOD_S),
    "pt2.lerp.b": lambda: GOOD_P2.lerp(BAD_P2, GOOD_S),
    "pt2.lerp.t": lambda: GOOD_P2.lerp(GOOD_P2, BAD_S),
    "pt2.midpoint": lambda: BAD_P2.midpoint(GOOD_P2),
    "pt2.disp.a": lambda: BAD_P2.displacement_to(GOOD_P2),
    "pt2.disp.b": lambda: GOOD_P2.displacement_to(BAD_P2),
    "pt2.at.coord": lambda: Point2.at(BAD_S, GOOD_S),
    "pt2.distance.a": lambda: BAD_P2.distance_to(GOOD_P2),
    "pt2.distance.b": lambda: GOOD_P2.distance_to(BAD_P2),
    "pt2.direction.a": lambda: BAD_P2.direction_to(GOOD_P2),
    "pt2.direction.b": lambda: GOOD_P2.direction_to(BAD_P2),
    "pt2.transformed.pt": lambda: BAD_P2.transformed_by(GOOD_T2),
    "pt2.transformed.tf": lambda: GOOD_P2.transformed_by(BAD_T2),
    "pt2.reflect.pt": lambda: BAD_P2.reflect_across(GOOD_P2),
    "pt2.reflect.center": lambda: GOOD_P2.reflect_across(BAD_P2),
    "line2.through.anchor": lambda: Line2.through(BAD_P2, GOOD_D2),
    "line2.through.axis": lambda: Line2.through(GOOD_P2, BAD_D2),
    "line2.through_points.a": lambda: Line2.through_points(BAD_P2, GOOD_P2),
    "line2.through_points.b": lambda: Line2.through_points(GOOD_P2, BAD_P2),
    "line2.direction": lambda: BAD_L2.direction(),
    "line2.origin": lambda: BAD_L2.origin(),
    "line2.normal": lambda: BAD_L2.normal(),
    "line2.project.line": lambda: BAD_L2.project(GOOD_P2),
    "line2.project.point": lambda: GOOD_L2.project(BAD_P2),
    "line2.signed_distance.line": lambda: BAD_L2.signed_distance(GOOD_P2),
    "line2.signed_distance.point": lambda: GOOD_L2.signed_distance(BAD_P2),
    "line2.distance_to.line": lambda: BAD_L2.distance_to(GOOD_P2),
    "line2.distance_to.point": lambda: GOOD_L2.distance_to(BAD_P2),
    "line2.contains": lambda: BAD_L2.contains(GOOD_P2),
    "line2.point_at": lambda: BAD_L2.point_at(1.0),
    "line2.intersect.first": lambda: BAD_L2.intersect(GOOD_L2),
    "line2.intersect.second": lambda: GOOD_L2.intersect(BAD_L2),
    "ray2.through.origin": lambda: Ray2.through(BAD_P2, GOOD_D2),
    "ray2.through.direction": lambda: Ray2.through(GOOD_P2, BAD_D2),
    "ray2.from_to.origin": lambda: Ray2.from_to(BAD_P2, GOOD_P2),
    "ray2.from_to.target": lambda: Ray2.from_to(GOOD_P2, BAD_P2),
    "ray2.origin": lambda: BAD_R2.origin(),
    "ray2.direction": lambda: BAD_R2.direction(),
    "ray2.project.ray": lambda: BAD_R2.project(GOOD_P2),
    "ray2.project.point": lambda: GOOD_R2.project(BAD_P2),
    "ray2.distance_to.ray": lambda: BAD_R2.distance_to(GOOD_P2),
    "ray2.distance_to.point": lambda: GOOD_R2.distance_to(BAD_P2),
    "ray2.contains": lambda: BAD_R2.contains(GOOD_P2),
    "ray2.point_at": lambda: BAD_R2.point_at(1.0),
    "ray2.reversed": lambda: BAD_R2.reversed(),
    "ray2.intersect.ray": lambda: BAD_R2.intersect(GOOD_L2),
    "ray2.intersect.line": lambda: GOOD_R2.intersect(BAD_L2),
    "segment2.between.start": lambda: Segment2.between(BAD_P2, GOOD_P2),
    "segment2.between.end": lambda: Segment2.between(GOOD_P2, BAD_P2),
    "segment2.start": lambda: BAD_SEG2.start(),
    "segment2.end": lambda: BAD_SEG2.end(),
    "segment2.direction": lambda: BAD_SEG2.direction(),
    "segment2.length": lambda: BAD_SEG2.length(),
    "segment2.midpoint": lambda: BAD_SEG2.midpoint(),
    "segment2.project.segment": lambda: BAD_SEG2.project(GOOD_P2),
    "segment2.project.point": lambda: GOOD_SEG2.project(BAD_P2),
    "segment2.distance_to.segment": lambda: BAD_SEG2.distance_to(GOOD_P2),
    "segment2.distance_to.point": lambda: GOOD_SEG2.distance_to(BAD_P2),
    "segment2.contains": lambda: BAD_SEG2.contains(GOOD_P2),
    "segment2.at": lambda: BAD_SEG2.at(0.5),
    "segment2.parameter_of.segment": lambda: BAD_SEG2.parameter_of(GOOD_P2),
    "segment2.parameter_of.point": lambda: GOOD_SEG2.parameter_of(BAD_P2),
    "segment2.reversed": lambda: BAD_SEG2.reversed(),
    # point
    "pt.midpoint.a": lambda: BAD_P.midpoint(GOOD_P),
    "pt.midpoint.b": lambda: GOOD_P.midpoint(BAD_P),
    "pt.lerp.t": lambda: GOOD_P.lerp(GOOD_P, BAD_S),
    "pt.disp.a": lambda: BAD_P.displacement_to(GOOD_P),
    "pt.disp.b": lambda: GOOD_P.displacement_to(BAD_P),
    "pt.translate": lambda: GOOD_P.translate(BAD_V3),
    "pt.at.coord": lambda: Point3.at(BAD_S, 0, 0),
    "pt.in_frame.local": lambda: Point3.in_frame(BAD_V3, GOOD_F),
    "pt.in_frame.frame": lambda: Point3.in_frame(GOOD_V3, BAD_F),
    "pt.coordinates_in.point": lambda: BAD_P.coordinates_in(GOOD_F),
    "pt.coordinates_in.frame": lambda: GOOD_P.coordinates_in(BAD_F),
    "pt.centroid": lambda: Point3.centroid([GOOD_P, BAD_P]),
    "pt.affine.point": lambda: Point3.affine([GOOD_P, BAD_P], [1, 1]),
    "pt.affine.weight": lambda: Point3.affine([GOOD_P, GOOD_P], [BAD_S, GOOD_S]),
    "pt.transformed.pt": lambda: BAD_P.transformed_by(GOOD_T),
    "pt.transformed.tf": lambda: GOOD_P.transformed_by(BAD_T),
    "pt.reflect.pt": lambda: BAD_P.reflect_across(GOOD_P),
    "pt.reflect.center": lambda: GOOD_P.reflect_across(BAD_P),
    # plane
    "plane.through.anchor": lambda: Plane.through(BAD_P, GOOD_D),
    "plane.through.axis": lambda: Plane.through(GOOD_P, BAD_D),
    "plane.through_points.a": lambda: Plane.through_points(BAD_P, GOOD_P, GOOD_P),
    "plane.through_points.b": lambda: Plane.through_points(GOOD_P, BAD_P, GOOD_P),
    "plane.through_points.c": lambda: Plane.through_points(GOOD_P, GOOD_P, BAD_P),
    "plane.spanned_by.anchor": lambda: Plane.spanned_by(BAD_P, GOOD_V3, GOOD_V3),
    "plane.spanned_by.u": lambda: Plane.spanned_by(GOOD_P, BAD_V3, GOOD_V3),
    "plane.spanned_by.v": lambda: Plane.spanned_by(GOOD_P, GOOD_V3, BAD_V3),
    "plane.normal": lambda: BAD_PLANE.normal(),
    "plane.origin": lambda: BAD_PLANE.origin(),
    "plane.project.plane": lambda: BAD_PLANE.project(GOOD_P),
    "plane.project.point": lambda: GOOD_PLANE.project(BAD_P),
    "plane.signed_distance.plane": lambda: BAD_PLANE.signed_distance(GOOD_P),
    "plane.signed_distance.point": lambda: GOOD_PLANE.signed_distance(BAD_P),
    "plane.distance_to": lambda: BAD_PLANE.distance_to(GOOD_P),
    "plane.contains": lambda: BAD_PLANE.contains(GOOD_P),
    "plane.facing.plane": lambda: BAD_PLANE.facing(GOOD_P),
    "plane.facing.point": lambda: GOOD_PLANE.facing(BAD_P),
    "plane.flipped": lambda: BAD_PLANE.flipped(),
    "plane.offset.plane": lambda: BAD_PLANE.offset(GOOD_S),
    "plane.offset.distance": lambda: GOOD_PLANE.offset(BAD_S),
    "plane.project_direction.plane": lambda: BAD_PLANE.project_direction(GOOD_D),
    "plane.project_direction.direction": lambda: GOOD_PLANE.project_direction(BAD_D),
    "plane.frame.plane": lambda: BAD_PLANE.frame(GOOD_P, GOOD_D),
    "plane.frame.origin": lambda: GOOD_PLANE.frame(BAD_P, GOOD_D),
    "plane.frame.tangent": lambda: GOOD_PLANE.frame(GOOD_P, BAD_D),
    "plane.winding_normal.plane": lambda: BAD_PLANE.winding_normal([GOOD_P, GOOD_P, GOOD_P]),
    "plane.winding_normal.points": lambda: GOOD_PLANE.winding_normal([GOOD_P, GOOD_P, BAD_P]),
    "plane.intersect.first": lambda: BAD_PLANE.intersect(GOOD_PLANE),
    "plane.intersect.second": lambda: GOOD_PLANE.intersect(BAD_PLANE),
    "plane.to_local.plane": lambda: BAD_PLANE.to_local(GOOD_P),
    "plane.to_local.point": lambda: GOOD_PLANE.to_local(BAD_P),
    "plane.embed.plane": lambda: BAD_PLANE.embed(GOOD_P2),
    "plane.embed.local": lambda: GOOD_PLANE.embed(BAD_P2),
    "line.through.anchor": lambda: Line.through(BAD_P, GOOD_D),
    "line.through.axis": lambda: Line.through(GOOD_P, BAD_D),
    "line.through_points.a": lambda: Line.through_points(BAD_P, GOOD_P),
    "line.through_points.b": lambda: Line.through_points(GOOD_P, BAD_P),
    "line.direction": lambda: BAD_LINE.direction(),
    "line.origin": lambda: BAD_LINE.origin(),
    "line.project.line": lambda: BAD_LINE.project(GOOD_P),
    "line.project.point": lambda: GOOD_LINE.project(BAD_P),
    "line.distance_to.line": lambda: BAD_LINE.distance_to(GOOD_P),
    "line.distance_to.point": lambda: GOOD_LINE.distance_to(BAD_P),
    "line.contains": lambda: BAD_LINE.contains(GOOD_P),
    "line.direction_along.line": lambda: BAD_LINE.direction_along([GOOD_P, GOOD_P]),
    "line.direction_along.points": lambda: GOOD_LINE.direction_along([GOOD_P, BAD_P]),
    "line.point_at": lambda: BAD_LINE.point_at(1.0),
    "ray.through.origin": lambda: Ray.through(BAD_P, GOOD_D),
    "ray.through.direction": lambda: Ray.through(GOOD_P, BAD_D),
    "ray.from_to.origin": lambda: Ray.from_to(BAD_P, GOOD_P),
    "ray.from_to.target": lambda: Ray.from_to(GOOD_P, BAD_P),
    "ray.origin": lambda: BAD_RAY.origin(),
    "ray.direction": lambda: BAD_RAY.direction(),
    "ray.project.ray": lambda: BAD_RAY.project(GOOD_P),
    "ray.project.point": lambda: GOOD_RAY.project(BAD_P),
    "ray.distance_to.ray": lambda: BAD_RAY.distance_to(GOOD_P),
    "ray.distance_to.point": lambda: GOOD_RAY.distance_to(BAD_P),
    "ray.contains": lambda: BAD_RAY.contains(GOOD_P),
    "ray.point_at": lambda: BAD_RAY.point_at(1.0),
    "ray.reversed": lambda: BAD_RAY.reversed(),
    "ray.intersect.ray": lambda: BAD_RAY.intersect(GOOD_PLANE),
    "ray.intersect.plane": lambda: GOOD_RAY.intersect(BAD_PLANE),
    "segment.between.start": lambda: Segment.between(BAD_P, GOOD_P),
    "segment.between.end": lambda: Segment.between(GOOD_P, BAD_P),
    "segment.start": lambda: BAD_SEG.start(),
    "segment.end": lambda: BAD_SEG.end(),
    "segment.direction": lambda: BAD_SEG.direction(),
    "segment.length": lambda: BAD_SEG.length(),
    "segment.midpoint": lambda: BAD_SEG.midpoint(),
    "segment.project.segment": lambda: BAD_SEG.project(GOOD_P),
    "segment.project.point": lambda: GOOD_SEG.project(BAD_P),
    "segment.distance_to.segment": lambda: BAD_SEG.distance_to(GOOD_P),
    "segment.distance_to.point": lambda: GOOD_SEG.distance_to(BAD_P),
    "segment.contains": lambda: BAD_SEG.contains(GOOD_P),
    "segment.at": lambda: BAD_SEG.at(0.5),
    "segment.parameter_of.segment": lambda: BAD_SEG.parameter_of(GOOD_P),
    "segment.parameter_of.point": lambda: GOOD_SEG.parameter_of(BAD_P),
    "segment.reversed": lambda: BAD_SEG.reversed(),
    # duration
    "duration.sum.lhs": lambda: BAD_DUR + GOOD_DUR,
    "duration.sum.rhs": lambda: GOOD_DUR + BAD_DUR,
    "duration.sub": lambda: GOOD_DUR - BAD_DUR,
    "duration.scaled.dur": lambda: BAD_DUR.scale(GOOD_S),
    "duration.scaled.factor": lambda: GOOD_DUR.scale(BAD_S),
    "duration.ratio.num": lambda: BAD_DUR.ratio(GOOD_DUR),
    "duration.ratio.den": lambda: GOOD_DUR.ratio(BAD_DUR),
    "duration.abs": lambda: abs(BAD_DUR),
    "duration.min.lhs": lambda: BAD_DUR.min(GOOD_DUR),
    "duration.min.rhs": lambda: GOOD_DUR.min(BAD_DUR),
    "duration.max.lhs": lambda: BAD_DUR.max(GOOD_DUR),
    "duration.max.rhs": lambda: GOOD_DUR.max(BAD_DUR),
    "duration.clamp.v": lambda: BAD_DUR.clamp(GOOD_DUR, GOOD_DUR),
    "duration.clamp.lo": lambda: GOOD_DUR.clamp(BAD_DUR, GOOD_DUR),
    "duration.clamp.hi": lambda: GOOD_DUR.clamp(GOOD_DUR, BAD_DUR),
    "duration.lt.lhs": lambda: BAD_DUR.lt(GOOD_DUR),
    "duration.lt.rhs": lambda: GOOD_DUR.lt(BAD_DUR),
    "duration.le.lhs": lambda: BAD_DUR.le(GOOD_DUR),
    "duration.le.rhs": lambda: GOOD_DUR.le(BAD_DUR),
    "duration.gt.lhs": lambda: BAD_DUR.gt(GOOD_DUR),
    "duration.gt.rhs": lambda: GOOD_DUR.gt(BAD_DUR),
    "duration.ge.lhs": lambda: BAD_DUR.ge(GOOD_DUR),
    "duration.ge.rhs": lambda: GOOD_DUR.ge(BAD_DUR),
    # instant
    "instant.shifted.instant": lambda: BAD_I.shifted_by(GOOD_DUR),
    "instant.shifted.by": lambda: GOOD_I.shifted_by(BAD_DUR),
    "instant.diff.later": lambda: GOOD_I.duration_to(BAD_I),
    "instant.diff.earlier": lambda: BAD_I.duration_to(GOOD_I),
    "instant.lerp.a": lambda: BAD_I.lerp(GOOD_I, GOOD_S),
    "instant.lerp.b": lambda: GOOD_I.lerp(BAD_I, GOOD_S),
    "instant.lerp.t": lambda: GOOD_I.lerp(GOOD_I, BAD_S),
    "instant.min.lhs": lambda: BAD_I.min(GOOD_I),
    "instant.min.rhs": lambda: GOOD_I.min(BAD_I),
    "instant.max.lhs": lambda: BAD_I.max(GOOD_I),
    "instant.max.rhs": lambda: GOOD_I.max(BAD_I),
    "instant.centroid": lambda: Instant.centroid([GOOD_I, BAD_I]),
    "instant.affine.instant": lambda: Instant.affine([GOOD_I, BAD_I], [1, 1]),
    "instant.affine.weight": lambda: Instant.affine([GOOD_I, GOOD_I], [BAD_S, GOOD_S]),
    "instant.before.lhs": lambda: BAD_I.before(GOOD_I),
    "instant.before.rhs": lambda: GOOD_I.before(BAD_I),
    "instant.after.lhs": lambda: BAD_I.after(GOOD_I),
    "instant.after.rhs": lambda: GOOD_I.after(BAD_I),
    # interval
    "interval.between.start": lambda: Interval.between(BAD_I, GOOD_I),
    "interval.between.end": lambda: Interval.between(GOOD_I, BAD_I),
    "interval.start": lambda: BAD_INT.start(),
    "interval.end": lambda: BAD_INT.end(),
    "interval.duration": lambda: BAD_INT.duration(),
    "interval.lerp.interval": lambda: BAD_INT.lerp(GOOD_S),
    "interval.lerp.t": lambda: GOOD_INT.lerp(BAD_S),
    "interval.intersection.a": lambda: BAD_INT.intersection(GOOD_INT),
    "interval.intersection.b": lambda: GOOD_INT.intersection(BAD_INT),
    "interval.hull.a": lambda: BAD_INT.hull(GOOD_INT2),
    "interval.hull.b": lambda: GOOD_INT.hull(BAD_INT),
    "interval.clamp.interval": lambda: BAD_INT.clamp(GOOD_I),
    "interval.clamp.instant": lambda: GOOD_INT.clamp(BAD_I),
    "interval.shifted.interval": lambda: BAD_INT.shifted(GOOD_DUR),
    "interval.shifted.by": lambda: GOOD_INT.shifted(BAD_DUR),
    "interval.expanded.interval": lambda: BAD_INT.expanded(GOOD_DUR),
    "interval.expanded.by": lambda: GOOD_INT.expanded(BAD_DUR),
    "interval.contains.interval": lambda: BAD_INT.contains(GOOD_I),
    "interval.contains.instant": lambda: GOOD_INT.contains(BAD_I),
    "interval.overlaps.a": lambda: BAD_INT.overlaps(GOOD_INT2),
    "interval.overlaps.b": lambda: GOOD_INT.overlaps(BAD_INT),
    # coverage
    "coverage.of.member": lambda: Coverage.of([BAD_INT]),
    "coverage.union.a": lambda: BAD_COV.union(GOOD_COV),
    "coverage.union.b": lambda: GOOD_COV.union(BAD_COV),
    "coverage.intersection.a": lambda: BAD_COV.intersection(GOOD_COV2),
    "coverage.intersection.b": lambda: GOOD_COV.intersection(BAD_COV),
    "coverage.difference.a": lambda: BAD_COV.difference(GOOD_COV2),
    "coverage.difference.b": lambda: GOOD_COV.difference(BAD_COV),
    "coverage.contains.coverage": lambda: BAD_COV.contains(GOOD_I),
    "coverage.contains.instant": lambda: GOOD_COV.contains(BAD_I),
    "coverage.total_duration": lambda: BAD_COV.total_duration(),
    "coverage.hull": lambda: BAD_COV.hull(),
    "coverage.gaps": lambda: BAD_COV.gaps(),
    # timemap
    "timemap.shift": lambda: TimeMap.shift(BAD_DUR),
    "timemap.rate": lambda: TimeMap.rate(BAD_S),
    "timemap.affine.offset": lambda: TimeMap.affine(BAD_DUR, GOOD_S),
    "timemap.affine.rate": lambda: TimeMap.affine(GOOD_DUR, BAD_S),
    "timemap.compose.outer": lambda: BAD_TM @ GOOD_TM,
    "timemap.compose.inner": lambda: GOOD_TM @ BAD_TM,
    "timemap.inverse": lambda: BAD_TM.inverse(),
    "timemap.aligning.source": lambda: TimeMap.aligning(BAD_S, GOOD_S),
    "timemap.aligning.target": lambda: TimeMap.aligning(GOOD_S, BAD_S),
    "timemap.through.first.source": lambda: TimeMap.through((BAD_S, GOOD_S), (GOOD_S, GOOD_S)),
    "timemap.through.first.target": lambda: TimeMap.through((GOOD_S, BAD_S), (GOOD_S, GOOD_S)),
    "timemap.through.second.source": lambda: TimeMap.through((GOOD_S, GOOD_S), (BAD_S, GOOD_S)),
    "timemap.through.second.target": lambda: TimeMap.through((GOOD_S, GOOD_S), (GOOD_S, BAD_S)),
    # roster (rung 3 — the entity-axis support set)
    "roster.union.a": lambda: BAD_ROSTER.union(GOOD_ROSTER),
    "roster.union.b": lambda: GOOD_ROSTER.union(BAD_ROSTER),
    "roster.intersection.a": lambda: BAD_ROSTER.intersection(GOOD_ROSTER),
    "roster.intersection.b": lambda: GOOD_ROSTER.intersection(BAD_ROSTER),
    "roster.difference.a": lambda: BAD_ROSTER.difference(GOOD_ROSTER),
    "roster.difference.b": lambda: GOOD_ROSTER.difference(BAD_ROSTER),
    "roster.count": lambda: BAD_ROSTER.count(),
    "roster.contains": lambda: BAD_ROSTER.contains(0),
    # rostermap (rung 3 — the entity-axis identity correspondence)
    "rostermap.identity.roster": lambda: RosterMap.identity(BAD_ROSTER),
    "rostermap.compose.outer": lambda: BAD_RMAP @ GOOD_RMAP,
    "rostermap.compose.inner": lambda: GOOD_RMAP @ BAD_RMAP,
    "rostermap.inverse": lambda: BAD_RMAP.inverse(),
    "rostermap.source": lambda: BAD_RMAP.source(),
    "rostermap.target": lambda: BAD_RMAP.target(),
    "rostermap.maps": lambda: BAD_RMAP.maps(0),
    # timewarp
    "timewarp.inverse": lambda: BAD_TW.inverse(),
    "timewarp.domain": lambda: BAD_TW.domain(),
    # timeline
    "timeline.derive.parent": lambda: BAD_TL.derive("x", GOOD_TM),
    "timeline.derive.by": lambda: GOOD_TL.derive("x", BAD_TM),
    "timeline.at.timeline": lambda: BAD_TL.at(GOOD_S),
    "timeline.at.local": lambda: GOOD_TL.at(BAD_S),
    "timeline.to_master": lambda: BAD_TL.to_master(),
    "timeline.relative_to.timeline": lambda: BAD_TL.relative_to(GOOD_TL),
    "timeline.relative_to.other": lambda: GOOD_TL.relative_to(BAD_TL),
    # sampling
    "sampling.uniform.interval": lambda: Sampling.uniform(BAD_INT, 3),
    "sampling.at_rate.rate": lambda: Sampling.at_rate(BAD_S, 3),
    "sampling.at_rate.start": lambda: Sampling.at_rate(60.0, 3, start=BAD_I),
    "sampling.span": lambda: BAD_SAMP.span(),
    "sampling.count": lambda: BAD_SAMP.count(),
    "sampling.rate": lambda: BAD_SAMP.rate(),
    # scalar signal
    "signal.sampled.sampling": lambda: ScalarSignal.sampled(BAD_SAMP, [1.0]),
    "signal.at.signal": lambda: BAD_SIG.at(GOOD_I),
    "signal.at.instant": lambda: GOOD_SIG.at(BAD_I),
    "signal.over": lambda: BAD_SIG.over(),
    "signal.resample.source": lambda: BAD_SIG.resample(GOOD_SAMP),
    "signal.resample.onto": lambda: GOOD_SIG.resample(BAD_SAMP),
    "signal.reparam.source": lambda: BAD_SIG.reparameterize(GOOD_TM),
    "signal.reparam.by": lambda: GOOD_SIG.reparameterize(BAD_TM),
    "signal.reparam.warp.source": lambda: BAD_SIG.reparameterize(GOOD_TW),
    "signal.reparam.warp.by": lambda: GOOD_SIG.reparameterize(BAD_TW),
    "signal.restrict.source": lambda: BAD_SIG.restrict(GOOD_INT),
    "signal.restrict.to": lambda: GOOD_SIG.restrict(BAD_INT),
    "signal.shift.source": lambda: BAD_SIG.shift(GOOD_DUR),
    "signal.shift.by": lambda: GOOD_SIG.shift(BAD_DUR),
    "signal.defined_at.signal": lambda: BAD_SIG.defined_at(GOOD_I),
    "signal.defined_at.instant": lambda: GOOD_SIG.defined_at(BAD_I),
    "signal.add.lhs": lambda: BAD_SIG + GOOD_SIG,
    "signal.add.rhs": lambda: GOOD_SIG + BAD_SIG,
    "signal.sub.lhs": lambda: BAD_SIG - GOOD_SIG,
    "signal.sub.rhs": lambda: GOOD_SIG - BAD_SIG,
    "signal.mul.lhs": lambda: BAD_SIG * GOOD_SIG,
    "signal.mul.rhs": lambda: GOOD_SIG * BAD_SIG,
    "signal.div.lhs": lambda: BAD_SIG / GOOD_SIG,
    "signal.div.rhs": lambda: GOOD_SIG / BAD_SIG,
    "signal.derivative": lambda: BAD_SIG.derivative(),
    "signal.map": lambda: BAD_SIG.map(lambda x: x),
    "signal.lift.source": lambda: ScalarSignal.lift([BAD_SIG], lambda x: x),
    "signal.constant": lambda: ScalarSignal.constant(1.0, BAD_INT),
    "signal.offset": lambda: BAD_SIG.offset(1.0),
    "signal.scale": lambda: BAD_SIG.scale(2.0),
    "vsignal.map": lambda: BAD_VSIG.map(lambda v: v),
    "vsignal.lift.source": lambda: Vec3Signal.lift([BAD_VSIG], lambda v: v),
    "psignal.map": lambda: BAD_PSIG.map(lambda p: p),
    "psignal.lift.source": lambda: Point3Signal.lift([BAD_PSIG], lambda p: p),
    "dsignal.map": lambda: BAD_DSIG.map(lambda d: d),
    "dsignal.lift.source": lambda: Direction3Signal.lift([BAD_DSIG], lambda d: d),
    "tsignal.map": lambda: BAD_TSIG.map(lambda t: t),
    "tsignal.lift.source": lambda: TransformSignal.lift([BAD_TSIG], lambda t: t),
    "signal.min_over.signal": lambda: BAD_SIG.min_over(GOOD_INT),
    "signal.min_over.window": lambda: GOOD_SIG.min_over(BAD_INT),
    "signal.max_over.signal": lambda: BAD_SIG.max_over(GOOD_INT),
    "signal.integral_over.signal": lambda: BAD_SIG.integral_over(GOOD_INT),
    "signal.mean_over.signal": lambda: BAD_SIG.mean_over(GOOD_INT),
    "signal.argmin_over.signal": lambda: BAD_SIG.argmin_over(GOOD_INT),
    "signal.argmin_over.window": lambda: GOOD_SIG.argmin_over(BAD_INT),
    "signal.argmax_over.signal": lambda: BAD_SIG.argmax_over(GOOD_INT),
    # bool signal (T3 — three-valued temporal predicate)
    "boolsig.lt": lambda: BAD_SIG.lt(0.0),
    "boolsig.at.signal": lambda: BAD_BOOLSIG.at(GOOD_I),
    "boolsig.at.instant": lambda: GOOD_BOOLSIG.at(BAD_I),
    "boolsig.support": lambda: BAD_BOOLSIG.support(),
    "boolsig.when_true": lambda: BAD_BOOLSIG.when_true(),
    "boolsig.when_false": lambda: BAD_BOOLSIG.when_false(),
    "boolsig.first_true": lambda: BAD_BOOLSIG.first_true(),
    "boolsig.last_true": lambda: BAD_BOOLSIG.last_true(),
    "boolsig.and.a": lambda: BAD_BOOLSIG.and_(GOOD_BOOLSIG),
    "boolsig.and.b": lambda: GOOD_BOOLSIG.and_(BAD_BOOLSIG),
    "boolsig.or": lambda: BAD_BOOLSIG.or_(GOOD_BOOLSIG),
    "boolsig.not": lambda: BAD_BOOLSIG.not_(),
    # vec3 signal
    "vsignal.sampled.sampling": lambda: Vec3Signal.sampled(BAD_SAMP, [[1.0, 0.0, 0.0]]),
    "vsignal.at.signal": lambda: BAD_VSIG.at(GOOD_I),
    "vsignal.at.instant": lambda: GOOD_VSIG.at(BAD_I),
    "vsignal.over": lambda: BAD_VSIG.over(),
    "vsignal.resample.source": lambda: BAD_VSIG.resample(GOOD_SAMP),
    "vsignal.resample.onto": lambda: GOOD_VSIG.resample(BAD_SAMP),
    "vsignal.reparam.source": lambda: BAD_VSIG.reparameterize(GOOD_TM),
    "vsignal.reparam.by": lambda: GOOD_VSIG.reparameterize(BAD_TM),
    "vsignal.restrict.source": lambda: BAD_VSIG.restrict(GOOD_INT),
    "vsignal.restrict.to": lambda: GOOD_VSIG.restrict(BAD_INT),
    "vsignal.shift.source": lambda: BAD_VSIG.shift(GOOD_DUR),
    "vsignal.shift.by": lambda: GOOD_VSIG.shift(BAD_DUR),
    "vsignal.defined_at.signal": lambda: BAD_VSIG.defined_at(GOOD_I),
    "vsignal.defined_at.instant": lambda: GOOD_VSIG.defined_at(BAD_I),
    "vsignal.add.lhs": lambda: BAD_VSIG + GOOD_VSIG,
    "vsignal.add.rhs": lambda: GOOD_VSIG + BAD_VSIG,
    "vsignal.sub.lhs": lambda: BAD_VSIG - GOOD_VSIG,
    "vsignal.sub.rhs": lambda: GOOD_VSIG - BAD_VSIG,
    "vsignal.dot.lhs": lambda: BAD_VSIG.dot(GOOD_VSIG),
    "vsignal.dot.rhs": lambda: GOOD_VSIG.dot(BAD_VSIG),
    "vsignal.norm": lambda: BAD_VSIG.norm(),
    "vsignal.derivative": lambda: BAD_VSIG.derivative(),
    # transport family (T1) — lift geometry through a pose signal
    "psignal.transformed_by.signal": lambda: BAD_PSIG.transformed_by(GOOD_TSIG),
    "psignal.transformed_by.pose": lambda: GOOD_PSIG.transformed_by(BAD_TSIG),
    "vsignal.transformed_by.signal": lambda: BAD_VSIG.transformed_by(GOOD_TSIG),
    "vsignal.transformed_by.pose": lambda: GOOD_VSIG.transformed_by(BAD_TSIG),
    "dsignal.rotated_by.signal": lambda: BAD_DSIG.rotated_by(GOOD_TSIG),
    "dsignal.rotated_by.pose": lambda: GOOD_DSIG.rotated_by(BAD_TSIG),
    "pbsignal.transformed_by.signal": lambda: BAD_PBS.transformed_by(GOOD_TSIG),
    "pbsignal.transformed_by.pose": lambda: GOOD_PBS.transformed_by(BAD_TSIG),
    "pbsignal.transformed_by_bundle.signal": lambda: BAD_PBS.transformed_by(GOOD_TBS),
    "pbsignal.transformed_by_bundle.poses": lambda: GOOD_PBS.transformed_by(BAD_TBS),
    "pbsignal.where.source": lambda: BAD_PBS.where([0]),
    "pbsignal.where.keys": lambda: GOOD_PBS.where(BAD_ROSTER),
    "pbsignal.relabel.source": lambda: BAD_PBS.relabel(GOOD_RMAP),
    "pbsignal.relabel.mapping": lambda: GOOD_PBS.relabel(BAD_RMAP),
    "pbsignal.fit_plane": lambda: BAD_PBS.fit_plane(),
    "pbsignal.centroid": lambda: BAD_PBS.centroid(),
    # plane signal (T8 — moving patch surface)
    "plsignal.sampled.sampling": lambda: PlaneSignal.sampled(BAD_SAMP, [_PLN]),
    "plsignal.at.signal": lambda: BAD_PLSIG.at(GOOD_I),
    "plsignal.at.instant": lambda: GOOD_PLSIG.at(BAD_I),
    "plsignal.normal": lambda: BAD_PLSIG.normal(),
    "plsignal.origin": lambda: BAD_PLSIG.origin(),
    "plsignal.signed_distance.plane": lambda: BAD_PLSIG.signed_distance(GOOD_PSIG),
    "plsignal.signed_distance.point": lambda: GOOD_PLSIG.signed_distance(BAD_PSIG),
    "plsignal.resample": lambda: BAD_PLSIG.resample(GOOD_SAMP),
    "plsignal.reparam": lambda: BAD_PLSIG.reparameterize(GOOD_TM),
    "plsignal.restrict": lambda: BAD_PLSIG.restrict(GOOD_INT),
    "plsignal.shift": lambda: BAD_PLSIG.shift(GOOD_DUR),
    "plsignal.signed_distance.cloud_plane": lambda: BAD_PLSIG.signed_distance(GOOD_PBS),
    "plsignal.signed_distance.cloud_arg": lambda: GOOD_PLSIG.signed_distance(BAD_PBS),
    # scalar bundle signal (T9 — folds for the contact spine)
    "sbsignal.at.signal": lambda: BAD_SBS.at(GOOD_I),
    "sbsignal.at.instant": lambda: GOOD_SBS.at(BAD_I),
    "sbsignal.min": lambda: BAD_SBS.min(),
    "sbsignal.max": lambda: BAD_SBS.max(),
    "sbsignal.mean": lambda: BAD_SBS.mean(),
    "sbsignal.sum": lambda: BAD_SBS.sum(),
    "sbsignal.count": lambda: BAD_SBS.count(),
    "sbsignal.resample": lambda: BAD_SBS.resample(GOOD_SAMP),
    "sbsignal.reparam": lambda: BAD_SBS.reparameterize(GOOD_TM),
    "sbsignal.restrict": lambda: BAD_SBS.restrict(GOOD_INT),
    "sbsignal.shift": lambda: BAD_SBS.shift(GOOD_DUR),
    # direction3 signal (the manifold case)
    "dsignal.sampled.sampling": lambda: Direction3Signal.sampled(BAD_SAMP, [[1.0, 0.0, 0.0]]),
    "dsignal.at.signal": lambda: BAD_DSIG.at(GOOD_I),
    "dsignal.at.instant": lambda: GOOD_DSIG.at(BAD_I),
    "dsignal.over": lambda: BAD_DSIG.over(),
    "dsignal.resample.source": lambda: BAD_DSIG.resample(GOOD_SAMP),
    "dsignal.resample.onto": lambda: GOOD_DSIG.resample(BAD_SAMP),
    "dsignal.reparam.source": lambda: BAD_DSIG.reparameterize(GOOD_TM),
    "dsignal.reparam.by": lambda: GOOD_DSIG.reparameterize(BAD_TM),
    "dsignal.restrict.source": lambda: BAD_DSIG.restrict(GOOD_INT),
    "dsignal.restrict.to": lambda: GOOD_DSIG.restrict(BAD_INT),
    "dsignal.shift.source": lambda: BAD_DSIG.shift(GOOD_DUR),
    "dsignal.shift.by": lambda: GOOD_DSIG.shift(BAD_DUR),
    "dsignal.defined_at.signal": lambda: BAD_DSIG.defined_at(GOOD_I),
    "dsignal.defined_at.instant": lambda: GOOD_DSIG.defined_at(BAD_I),
    # transform signal (SE(3))
    "tsignal.sampled.sampling": lambda: TransformSignal.sampled(BAD_SAMP, [_ID]),
    "tsignal.at.signal": lambda: BAD_TSIG.at(GOOD_I),
    "tsignal.at.instant": lambda: GOOD_TSIG.at(BAD_I),
    "tsignal.over": lambda: BAD_TSIG.over(),
    "tsignal.resample.source": lambda: BAD_TSIG.resample(GOOD_SAMP),
    "tsignal.resample.onto": lambda: GOOD_TSIG.resample(BAD_SAMP),
    "tsignal.reparam.source": lambda: BAD_TSIG.reparameterize(GOOD_TM),
    "tsignal.reparam.by": lambda: GOOD_TSIG.reparameterize(BAD_TM),
    "tsignal.restrict.source": lambda: BAD_TSIG.restrict(GOOD_INT),
    "tsignal.restrict.to": lambda: GOOD_TSIG.restrict(BAD_INT),
    "tsignal.shift.source": lambda: BAD_TSIG.shift(GOOD_DUR),
    "tsignal.shift.by": lambda: GOOD_TSIG.shift(BAD_DUR),
    "tsignal.defined_at.signal": lambda: BAD_TSIG.defined_at(GOOD_I),
    "tsignal.defined_at.instant": lambda: GOOD_TSIG.defined_at(BAD_I),
    "tsignal.angular_velocity": lambda: BAD_TSIG.angular_velocity(),
    "tsignal.velocity": lambda: BAD_TSIG.velocity(),
    "tsignal.angular_speed": lambda: BAD_TSIG.angular_speed(),
    # point3 signal (framed; grounding partiality)
    "psignal.at.signal": lambda: BAD_PSIG.at(GOOD_I),
    "psignal.at.instant": lambda: GOOD_PSIG.at(BAD_I),
    "psignal.over": lambda: BAD_PSIG.over(),
    "psignal.resample.source": lambda: BAD_PSIG.resample(GOOD_SAMP),
    "psignal.resample.onto": lambda: GOOD_PSIG.resample(BAD_SAMP),
    "psignal.reparam.source": lambda: BAD_PSIG.reparameterize(GOOD_TM),
    "psignal.reparam.by": lambda: GOOD_PSIG.reparameterize(BAD_TM),
    "psignal.restrict.source": lambda: BAD_PSIG.restrict(GOOD_INT),
    "psignal.restrict.to": lambda: GOOD_PSIG.restrict(BAD_INT),
    "psignal.shift.source": lambda: BAD_PSIG.shift(GOOD_DUR),
    "psignal.shift.by": lambda: GOOD_PSIG.shift(BAD_DUR),
    "psignal.defined_at.signal": lambda: BAD_PSIG.defined_at(GOOD_I),
    "psignal.defined_at.instant": lambda: GOOD_PSIG.defined_at(BAD_I),
    "psignal.displacement.lhs": lambda: BAD_PSIG.displacement_to(GOOD_PSIG),
    "psignal.displacement.rhs": lambda: GOOD_PSIG.displacement_to(BAD_PSIG),
    "psignal.distance.lhs": lambda: BAD_PSIG.distance_to(GOOD_PSIG),
    "psignal.distance.rhs": lambda: GOOD_PSIG.distance_to(BAD_PSIG),
    "psignal.velocity": lambda: BAD_PSIG.velocity(),
    "psignal.speed": lambda: BAD_PSIG.speed(),
    # point3 bundle
    "bundle.of": lambda: Point3Bundle.of([BAD_P]),
    "bundle.at": lambda: BAD_BUNDLE.at(0),
    "bundle.present": lambda: BAD_BUNDLE.present(0),
    "bundle.count": lambda: BAD_BUNDLE.count(),
    "bundle.where": lambda: BAD_BUNDLE.where([0]),
    "bundle.support": lambda: BAD_BUNDLE.support(),
    "bundle.relabel.source": lambda: BAD_BUNDLE.relabel(GOOD_RMAP),
    "bundle.relabel.mapping": lambda: GOOD_PB.relabel(BAD_RMAP),
    "bundle.centroid": lambda: BAD_BUNDLE.centroid(),
    "bundle.fit_plane": lambda: BAD_BUNDLE.fit_plane(),
    "bundle.fit_line": lambda: BAD_BUNDLE.fit_line(),
    "bundle.in_frame.source": lambda: BAD_BUNDLE.in_frame(GOOD_PLANE),
    "bundle.in_frame.plane": lambda: GOOD_PB.in_frame(BAD_PLANE),
    "bundle.transformed_by_bundle.source": lambda: BAD_BUNDLE.transformed_by(GOOD_TB),
    "bundle.transformed_by_bundle.transforms": lambda: GOOD_PB.transformed_by(BAD_TB),
    # bundle query layer (C1-C7) + plane broadcasts (G7)
    "bundle.presence_mask": lambda: BAD_BUNDLE.presence_mask(),
    "bundle.all_present": lambda: BAD_BUNDLE.all_present(),
    "bundle.any_present": lambda: BAD_BUNDLE.any_present(),
    "bundle.where_roster": lambda: GOOD_PB.where(BAD_ROSTER),
    "bundle.map_scalar": lambda: BAD_BUNDLE.map_scalar(lambda p: p.distance_to(GOOD_P)),
    "bundle.map_point": lambda: BAD_BUNDLE.map_point(lambda p: p),
    "bundle.map_vec3": lambda: BAD_BUNDLE.map_vec3(lambda p: p.displacement_to(GOOD_P)),
    "bundle.distances_to.cloud": lambda: BAD_BUNDLE.distances_to(GOOD_P),
    "bundle.distances_to.point": lambda: GOOD_PB.distances_to(BAD_P),
    "bundle.closest_point_to.cloud": lambda: BAD_BUNDLE.closest_point_to(GOOD_P),
    "bundle.closest_point_to.point": lambda: GOOD_PB.closest_point_to(BAD_P),
    "bundle.nearest_to": lambda: BAD_BUNDLE.nearest_to(GOOD_P),
    "bundle.bounds": lambda: BAD_BUNDLE.bounds(),
    "p2bundle.bounds": lambda: BAD_P2B.bounds(),
    "sbundle.argmin": lambda: BAD_SB.argmin(),
    "sbundle.argmax": lambda: BAD_SB.argmax(),
    "boolbundle.of": lambda: BoolBundle.of([BAD_BOOL]),
    "boolbundle.at": lambda: BAD_BB.at(0),
    "boolbundle.where": lambda: BAD_BB.where([0]),
    "boolbundle.and.a": lambda: BAD_BB.and_(GOOD_BB),
    "boolbundle.and.b": lambda: GOOD_BB.and_(BAD_BB),
    "boolbundle.or": lambda: BAD_BB.or_(GOOD_BB),
    "boolbundle.not": lambda: BAD_BB.not_(),
    "boolbundle.any": lambda: BAD_BB.any(),
    "boolbundle.all": lambda: BAD_BB.all(),
    "boolbundle.relabel.source": lambda: BAD_BB.relabel(GOOD_RMAP),
    "boolbundle.relabel.mapping": lambda: GOOD_BB.relabel(BAD_RMAP),
    "plane.signed_distance.cloud_plane": lambda: BAD_PLANE.signed_distance(GOOD_PB),
    "plane.signed_distance.cloud_arg": lambda: GOOD_PLANE.signed_distance(BAD_BUNDLE),
    "plane.project.cloud_plane": lambda: BAD_PLANE.project(GOOD_PB),
    "plane.project.cloud_arg": lambda: GOOD_PLANE.project(BAD_BUNDLE),
    "plane.contains.cloud_plane": lambda: BAD_PLANE.contains(GOOD_PB),
    "plane.contains.cloud_arg": lambda: GOOD_PLANE.contains(BAD_BUNDLE),
    # point2 bundle
    "p2bundle.of": lambda: Point2Bundle.of([BAD_P2]),
    "p2bundle.at": lambda: BAD_P2B.at(0),
    "p2bundle.where": lambda: BAD_P2B.where([0]),
    "p2bundle.relabel.source": lambda: BAD_P2B.relabel(GOOD_RMAP),
    "p2bundle.relabel.mapping": lambda: GOOD_P2B.relabel(BAD_RMAP),
    "p2bundle.centroid": lambda: BAD_P2B.centroid(),
    "p2bundle.transformed_by.source": lambda: BAD_P2B.transformed_by(GOOD_T2),
    "p2bundle.transformed_by.transform": lambda: GOOD_P2B.transformed_by(BAD_T2),
    "p2bundle.distance_to.a": lambda: BAD_P2B.distance_to(GOOD_P2B),
    "p2bundle.distance_to.b": lambda: GOOD_P2B.distance_to(BAD_P2B),
    "p2bundle.map_scalar": lambda: BAD_P2B.map_scalar(lambda p: p.distance_to(GOOD_P2)),
    "p2bundle.map_point": lambda: BAD_P2B.map_point(lambda p: p.translate((1, 1))),
    "p2bundle.distances_to.cloud": lambda: BAD_P2B.distances_to(GOOD_P2),
    "p2bundle.distances_to.point": lambda: GOOD_P2B.distances_to(BAD_P2),
    "p2bundle.closest_point_to.cloud": lambda: BAD_P2B.closest_point_to(GOOD_P2),
    "p2bundle.closest_point_to.point": lambda: GOOD_P2B.closest_point_to(BAD_P2),
    "p2bundle.nearest_to.cloud": lambda: BAD_P2B.nearest_to(GOOD_P2),
    "p2bundle.nearest_to.point": lambda: GOOD_P2B.nearest_to(BAD_P2),
    # region2
    "region2.polygon": lambda: Region2.polygon([BAD_P2, GOOD_P2, Point2.at(1, 0)]),
    "region2.hull.points": lambda: Region2.hull([BAD_P2, GOOD_P2, Point2.at(1, 0)]),
    "region2.hull.cloud": lambda: Region2.hull(BAD_P2B),
    "region2.contains.region": lambda: BAD_REGION.contains(GOOD_P2),
    "region2.contains.point": lambda: GOOD_REGION.contains(BAD_P2),
    "region2.area": lambda: BAD_REGION.area(),
    "region2.centroid": lambda: BAD_REGION.centroid(),
    "region2.vertices": lambda: BAD_REGION.vertices(),
    "region2.bounds": lambda: BAD_REGION.bounds(),
    "region2.offset": lambda: BAD_REGION.offset(-0.1),
    "region2.union.a": lambda: BAD_REGION.union(GOOD_REGION),
    "region2.union.b": lambda: GOOD_REGION.union(BAD_REGION),
    "region2.intersection.a": lambda: BAD_REGION.intersection(GOOD_REGION),
    "region2.intersection.b": lambda: GOOD_REGION.intersection(BAD_REGION),
    "region2.difference.a": lambda: BAD_REGION.difference(GOOD_REGION),
    "region2.difference.b": lambda: GOOD_REGION.difference(BAD_REGION),
    "region2.sample": lambda: BAD_REGION.sample(4),
    "region2.corners": lambda: BAD_REGION.corners(),
    "region2.transformed_by.region": lambda: BAD_REGION.transformed_by(GOOD_T2),
    "region2.transformed_by.transform": lambda: GOOD_REGION.transformed_by(BAD_T2),
    "region2.signed_distance.region": lambda: BAD_REGION.signed_distance(GOOD_P2),
    "region2.signed_distance.point": lambda: GOOD_REGION.signed_distance(BAD_P2),
    "region2.nearest_boundary_point.region": lambda: BAD_REGION.nearest_boundary_point(GOOD_P2),
    "region2.nearest_boundary_point.point": lambda: GOOD_REGION.nearest_boundary_point(BAD_P2),
    "region2.perimeter": lambda: BAD_REGION.perimeter(),
    "region2.symmetric_difference.a": lambda: BAD_REGION.symmetric_difference(GOOD_REGION),
    "region2.symmetric_difference.b": lambda: GOOD_REGION.symmetric_difference(BAD_REGION),
    "region2.intersects.a": lambda: BAD_REGION.intersects(GOOD_REGION),
    "region2.intersects.b": lambda: GOOD_REGION.intersects(BAD_REGION),
    "region2.contains_region.a": lambda: BAD_REGION.contains_region(GOOD_REGION),
    "region2.contains_region.b": lambda: GOOD_REGION.contains_region(BAD_REGION),
    "region2.closest_point.region": lambda: BAD_REGION.closest_point(GOOD_P2),
    "region2.closest_point.point": lambda: GOOD_REGION.closest_point(BAD_P2),
    "plane.transformed_by.plane": lambda: BAD_PLANE.transformed_by(GOOD_T),
    "plane.transformed_by.transform": lambda: GOOD_PLANE.transformed_by(BAD_T),
    # face (oriented bounded patch)
    "face.on.plane": lambda: Face.on(BAD_PLANE, GOOD_REGION),
    "face.on.region": lambda: Face.on(GOOD_PLANE, BAD_REGION),
    "face.plane": lambda: BAD_FACE.plane(),
    "face.region": lambda: BAD_FACE.region(),
    "face.closest_point.face": lambda: BAD_FACE.closest_point(GOOD_P),
    "face.closest_point.point": lambda: GOOD_FACE.closest_point(BAD_P),
    "face.clearance.face": lambda: BAD_FACE.clearance(GOOD_P),
    "face.clearance.point": lambda: GOOD_FACE.clearance(BAD_P),
    "face.contains.face": lambda: BAD_FACE.contains(GOOD_P),
    "face.contains.point": lambda: GOOD_FACE.contains(BAD_P),
    "face.transformed_by.face": lambda: BAD_FACE.transformed_by(GOOD_T),
    "face.transformed_by.transform": lambda: GOOD_FACE.transformed_by(BAD_T),
    "face.frame": lambda: BAD_FACE.frame(),
    "face.boundary": lambda: BAD_FACE.boundary(),
    "face.clearance.cloud": lambda: GOOD_FACE.clearance(BAD_BUNDLE),
    # FaceSignal (the moving patch)
    "facesignal.of.face": lambda: FaceSignal.of(BAD_FACE, GOOD_TSIG),
    "facesignal.of.pose": lambda: FaceSignal.of(GOOD_FACE, BAD_TSIG),
    "facesignal.at.signal": lambda: BAD_FSIG.at(0.5),
    "facesignal.at.instant": lambda: GOOD_FSIG.at(BAD_I),
    "facesignal.region": lambda: FaceSignal.of(BAD_FACE, GOOD_TSIG).region(),
    "facesignal.plane": lambda: BAD_FSIG.plane(),
    "facesignal.frame": lambda: BAD_FSIG.frame(),
    "facesignal.boundary": lambda: BAD_FSIG.boundary(),
    "facesignal.boundary.face": lambda: FaceSignal.of(BAD_FACE, GOOD_TSIG).boundary(),
    "facesignal.clearance.signal": lambda: BAD_FSIG.clearance(GOOD_PSIG),
    "facesignal.clearance.point": lambda: GOOD_FSIG.clearance(BAD_PSIG),
    "facesignal.clearance_cloud.signal": lambda: BAD_FSIG.clearance(GOOD_PBS),
    "facesignal.clearance_cloud.cloud": lambda: GOOD_FSIG.clearance(BAD_PBS),
    "facesignal.contains.signal": lambda: BAD_FSIG.contains(GOOD_PSIG),
    "facesignal.contains.point": lambda: GOOD_FSIG.contains(BAD_PSIG),
    # other bundle facades
    "vbundle.of": lambda: Vec3Bundle.of([BAD_V3]),
    "vbundle.at": lambda: BAD_VB.at(0),
    "vbundle.where": lambda: BAD_VB.where([0]),
    "vbundle.relabel.source": lambda: BAD_VB.relabel(GOOD_RMAP),
    "vbundle.relabel.mapping": lambda: GOOD_VB.relabel(BAD_RMAP),
    "vbundle.mean": lambda: BAD_VB.mean(),
    "sbundle.of": lambda: ScalarBundle.of([BAD_S]),
    "sbundle.at": lambda: BAD_SB.at(0),
    "sbundle.where": lambda: BAD_SB.where([0]),
    "sbundle.relabel.source": lambda: BAD_SB.relabel(GOOD_RMAP),
    "sbundle.relabel.mapping": lambda: GOOD_SB.relabel(BAD_RMAP),
    "sbundle.mean": lambda: BAD_SB.mean(),
    "dbundle.of": lambda: Direction3Bundle.of([BAD_D]),
    "dbundle.at": lambda: BAD_DB.at(0),
    "dbundle.where": lambda: BAD_DB.where([0]),
    "dbundle.relabel.source": lambda: BAD_DB.relabel(GOOD_RMAP),
    "dbundle.relabel.mapping": lambda: GOOD_DB.relabel(BAD_RMAP),
    "dbundle.mean": lambda: BAD_DB.mean(),
    "tbundle.of": lambda: TransformBundle.of([BAD_T]),
    "tbundle.at": lambda: BAD_TB.at(0),
    "tbundle.where": lambda: BAD_TB.where([0]),
    "tbundle.relabel.source": lambda: BAD_TB.relabel(GOOD_RMAP),
    "tbundle.relabel.mapping": lambda: GOOD_TB.relabel(BAD_RMAP),
    # bundle algebra — zip (lift), folds, broadcast
    "sbundle.add.lhs": lambda: BAD_SB + GOOD_SB,
    "sbundle.add.rhs": lambda: GOOD_SB + BAD_SB,
    "sbundle.sub.lhs": lambda: BAD_SB - GOOD_SB,
    "sbundle.sub.rhs": lambda: GOOD_SB - BAD_SB,
    "sbundle.mul.lhs": lambda: BAD_SB * GOOD_SB,
    "sbundle.mul.rhs": lambda: GOOD_SB * BAD_SB,
    "sbundle.div.num": lambda: BAD_SB / GOOD_SB,
    "sbundle.div.den": lambda: GOOD_SB / BAD_SB,
    "sbundle.sum": lambda: BAD_SB.sum(),
    "sbundle.min": lambda: BAD_SB.min(),
    "sbundle.max": lambda: BAD_SB.max(),
    "vbundle.add.lhs": lambda: BAD_VB + GOOD_VB,
    "vbundle.add.rhs": lambda: GOOD_VB + BAD_VB,
    "vbundle.sub.lhs": lambda: BAD_VB - GOOD_VB,
    "vbundle.sub.rhs": lambda: GOOD_VB - BAD_VB,
    "vbundle.dot.lhs": lambda: BAD_VB.dot(GOOD_VB),
    "vbundle.dot.rhs": lambda: GOOD_VB.dot(BAD_VB),
    "vbundle.sum": lambda: BAD_VB.sum(),
    "vbundle.norm": lambda: BAD_VB.norm(),
    "pbundle.displacement.lhs": lambda: BAD_BUNDLE.displacement_to(GOOD_PB),
    "pbundle.displacement.rhs": lambda: GOOD_PB.displacement_to(BAD_BUNDLE),
    "pbundle.distance.lhs": lambda: BAD_BUNDLE.distance_to(GOOD_PB),
    "pbundle.distance.rhs": lambda: GOOD_PB.distance_to(BAD_BUNDLE),
    "pbundle.transformed_by.source": lambda: BAD_BUNDLE.transformed_by(GOOD_T),
    "pbundle.transformed_by.transform": lambda: GOOD_PB.transformed_by(BAD_T),
    # point3 bundle signal (collection over time)
    "pbsignal.from_frames.sampling": lambda: Point3BundleSignal.from_frames([1, 0], [[[0, 0, 0]], [[1, 0, 0]]]),
    "pbsignal.at.signal": lambda: BAD_PBS.at(GOOD_I),
    "pbsignal.at.instant": lambda: GOOD_PBS.at(BAD_I),
    "pbsignal.key.source": lambda: BAD_PBS.key(0),
    "pbsignal.over": lambda: BAD_PBS.over(),
    "pbsignal.resample.source": lambda: BAD_PBS.resample(GOOD_SAMP),
    "pbsignal.resample.onto": lambda: GOOD_PBS.resample(BAD_SAMP),
    "pbsignal.reparam.source": lambda: BAD_PBS.reparameterize(GOOD_TM),
    "pbsignal.reparam.by": lambda: GOOD_PBS.reparameterize(BAD_TM),
    "pbsignal.reparam.warp": lambda: GOOD_PBS.reparameterize(BAD_TW),
    "pbsignal.restrict.source": lambda: BAD_PBS.restrict(GOOD_INT),
    "pbsignal.restrict.to": lambda: GOOD_PBS.restrict(BAD_INT),
    "pbsignal.shift.source": lambda: BAD_PBS.shift(GOOD_DUR),
    "pbsignal.shift.by": lambda: GOOD_PBS.shift(BAD_DUR),
    # transform bundle signal (pose-set over time; no key() — partial SE(3) blend)
    "tbsignal.from_frames.sampling": lambda: TransformBundleSignal.from_frames([1, 0], [[GOOD_T], [GOOD_T]]),
    "tbsignal.from_frames.member": lambda: TransformBundleSignal.from_frames([0, 1], [[BAD_T], [GOOD_T]]),
    "tbsignal.from_matrices.sampling": lambda: TransformBundleSignal.from_matrices(
        [1, 0], [[GOOD_T.resolve().matrix], [GOOD_T.resolve().matrix]]
    ),
    "tbsignal.at.signal": lambda: BAD_TBS.at(GOOD_I),
    "tbsignal.at.instant": lambda: GOOD_TBS.at(BAD_I),
    "tbsignal.over": lambda: BAD_TBS.over(),
    "tbsignal.resample.source": lambda: BAD_TBS.resample(GOOD_SAMP),
    "tbsignal.resample.onto": lambda: GOOD_TBS.resample(BAD_SAMP),
    "tbsignal.reparam.source": lambda: BAD_TBS.reparameterize(GOOD_TM),
    "tbsignal.reparam.by": lambda: GOOD_TBS.reparameterize(BAD_TM),
    "tbsignal.reparam.warp": lambda: GOOD_TBS.reparameterize(BAD_TW),
    "tbsignal.restrict.source": lambda: BAD_TBS.restrict(GOOD_INT),
    "tbsignal.restrict.to": lambda: GOOD_TBS.restrict(BAD_INT),
    "tbsignal.shift.source": lambda: BAD_TBS.shift(GOOD_DUR),
    "tbsignal.shift.by": lambda: GOOD_TBS.shift(BAD_DUR),
    "tbsignal.where.source": lambda: BAD_TBS.where([0]),
    "tbsignal.where.keys": lambda: GOOD_TBS.where(BAD_ROSTER),
    "tbsignal.relabel.source": lambda: BAD_TBS.relabel(GOOD_RMAP),
    "tbsignal.relabel.mapping": lambda: GOOD_TBS.relabel(BAD_RMAP),
    "tbsignal.key": lambda: BAD_TBS.key(0),
}


@pytest.mark.parametrize("thunk", CASES.values(), ids=list(CASES))
def test_unresolvability_propagates(thunk: Callable[[], object]) -> None:
    assert isinstance(thunk().decide(), Unresolvable)  # type: ignore[attr-defined]
