"""fungeom — a functional geometry API.

Geometry is described as an immutable, lazily-evaluated graph of resolvers. Each
primitive is one class — ``Scalar``, ``Vec2``, ``Vec3``, ``Direction3``,
``Transform``, ``Frame``, ``Point3`` — that you both construct from (classmethods
like ``Vec3.of`` / ``Point3.at``) and compose with (fluent methods like
``a.midpoint(b)``). Build a graph, ``decide()`` whether it can be resolved, then
``resolve()`` to get a concrete value (reachable as ``<Primitive>.Value``).

The decidability core (``Resolver``, ``Resolvable``, ``Unresolvable``,
``gather``) is public; the concrete resolvers behind each facade are not.
"""

from fungeom.core import (
    Resolvability,
    Resolvable,
    Resolver,
    Unresolvable,
    UnresolvableError,
    gather,
)
from fungeom.primitives import (
    MASTER_CLOCK,
    WORLD_FRAME,
    WORLD_FRAME2,
    AffineTimeMap,
    Bool,
    Boundary,
    Clock,
    CoordinateFrame,
    CoordinateFrame2,
    Direction3Signal,
    Coverage,
    CoverageValue,
    Direction2,
    Direction2Value,
    Direction3,
    Duration,
    Frame,
    Frame2,
    Instant,
    Interpolation,
    Interval,
    IntervalValue,
    Line,
    LineValue,
    Mat3,
    Mat4,
    Plane,
    PlaneValue,
    Point2,
    Point2Value,
    Point3,
    Point3Signal,
    Ray,
    RayValue,
    Mat2,
    RigidTransform,
    RigidTransform2,
    Segment,
    SegmentValue,
    Transform2,
    SampledSeries,
    Sampling,
    SamplingValue,
    Scalar,
    ScalarSignal,
    Bundle,
    BundleValue,
    Direction3Bundle,
    PiecewiseLinearWarp,
    Point3Bundle,
    Point3BundleSignal,
    ScalarBundle,
    TransformBundle,
    Vec3Bundle,
    TimeMap,
    TimeWarp,
    Timeline,
    Transform,
    TransformSignal,
    Vec2,
    Vec3,
    Vec3Signal,
)
from fungeom.viz import render_tree, resolver_tree

__all__ = [
    # primitives (facades)
    "Bool",
    "Scalar",
    "Vec2",
    "Vec3",
    "Direction2",
    "Direction3",
    "Transform",
    "Transform2",
    "Frame",
    "Frame2",
    "Point2",
    "Point3",
    "Plane",
    "Line",
    "Ray",
    "Segment",
    # temporal
    "Duration",
    "Instant",
    "Interval",
    "Coverage",
    "TimeMap",
    "TimeWarp",
    "Timeline",
    "Sampling",
    "Bundle",
    "ScalarBundle",
    "Vec3Bundle",
    "Direction3Bundle",
    "TransformBundle",
    "Point3Bundle",
    "Point3BundleSignal",
    "Interpolation",
    "Boundary",
    "ScalarSignal",
    "Vec3Signal",
    "Direction3Signal",
    "TransformSignal",
    "Point3Signal",
    # commonly-used value types
    "RigidTransform",
    "RigidTransform2",
    "Mat2",
    "Point2Value",
    "PlaneValue",
    "LineValue",
    "RayValue",
    "SegmentValue",
    "Direction2Value",
    "CoordinateFrame",
    "WORLD_FRAME",
    "CoordinateFrame2",
    "WORLD_FRAME2",
    "IntervalValue",
    "CoverageValue",
    "AffineTimeMap",
    "PiecewiseLinearWarp",
    "BundleValue",
    "Clock",
    "MASTER_CLOCK",
    "SamplingValue",
    "SampledSeries",
    "Mat3",
    "Mat4",
    # decidability core
    "Resolver",
    "Resolvability",
    "Resolvable",
    "Unresolvable",
    "UnresolvableError",
    "gather",
    # visualization
    "resolver_tree",
    "render_tree",
]
